### PR TITLE
#1212 - Zero-width spans for PDF editor

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- fix typo Mpaping -> Mapping in PdfExtractFile.java
- enable rendering of zero-width span annotations in PDF editor
- fix tests to match this changes
- add support for creating zero-width spans with shift + left click in PDF editor

**How to test manually**
- Open PDF document in PDF editor
- Create zero width span with shift + left click

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
@wpmp is it still WIP?

**Comment by wpmp** [comment]
@reckart yes, still WIP.
Rendering of existing zero width spans works, however creating them does not work yet

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Pull request merged**
