### PR TITLE
#1747 Curation sidebar causes very large projects to hang

### PR DESCRIPTION
**Pull request by UWinch**
**What's in the PR**
Don't overwrite `onConfigure` for visibility of components, use behaviours instead to avoid calling `getModelObject` which loads the components' model each time.

**How to test manually**
* Have the curation sidebar enabled with `curation.sidebar.enabled=true` in the settings.properties file
* Go to annotation page
* Open and close the curation sidebar once
* Switch to the next document 

**Automatic testing**
* [x] PR updates unit tests

### CODE REVIEW

**Comment by reckart** [comment]
Screenshot 2020-06-23 at 11 58 00

If you check the profiling screenshot in the initial comment, you can see that a problem is caused by `listUsers` calling `userRepository.getCurrentUser()` and `hasFinishedDoc` for each user. So `userRepository.getCurrentUser()` does a DB access. Then also, each time `hasFinishedDoc` is called, two database accesses are done using `existsAnnotationDocument` and then `getAnnotationDocument`. So let's say we have 300 annotators on a project, then we make 900 database accesses here.

Btw. I can see that there are many cases where `getCurrentUser()` is called just to get the current users username. Maybe we should have a `getCurrentUsername()` which would only need to access the security context and not access the DB at all... that might speed of a few things.

**Comment by UWinch** [comment]
Jenkins, can you test this please?

**Comment by jcklie** [comment]
@UWinch Did you fix the looped DB access?

**Comment by UWinch** [comment]
I changed the loop in `CurationSidebar` line 351 to line 338 which calls one db query now via ` curationService.listFinishedUsers` .

**Comment by jcklie** [comment]
Works for me

**Pull request merged**
