### PR TITLE
Feature/4 ability to disable kbs

### PR DESCRIPTION
**Pull request by reckart**
- added "enabled" field for KBs
- added a method to fetch only the enabled KBs.
- added corresponding "enabled"-Checkbox in project configurations UI
- changed/adapted other related methods/classes to handle "enabled"-value

See: #4

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@MdeBoer95 @Rentier Jenkins fails due to Checkstyle/formatting problems (tab characters). 

Please check out this branch, fix the formatting, and commit the fixes. Use the right title line for the commit message, e.g.:

```
#4 - Ability to disable KBs 

- Checkstyle fixes
```

**Comment by MdeBoer95** [comment]
Shall I push to this GitHub branch or to the GitLab?
My Checkstyle isn't working as it used to, that's why i didn't see the tab.

**Comment by reckart** [comment]
@MdeBoer95 best check out a fresh clone from the GitHub repo, make the changes there in the branch and then push back to GitHub.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@MdeBoer95 still checkstyle issues. Best try running a Maven build on the command line if your Eclipse-based setup currently does not work.

**Comment by MdeBoer95** [comment]
I think my CheckStyle works correctly again. I removed an unused import that it complained about.
I hope that's it now.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
All ok. Branch merged. Thanks!

**Pull request merged**
