### PR TITLE
#1173 - Exception when linked entity spans lines

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Check for exact / contains / startswith using regular expression and be resilient against different types of whitespace appearing in the query / match
- Collapse whitespace during sanitation
- Also sanitize control characters away

**How to test manually**
* Try linking an entity annotation which crosses a line break

**Automatic testing**
* [x] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by jcklie** [comment]
I use Wikidata Official. When I change the NER layer to allow cross sentence and annotate "country. The French" in "Emmanuel_Macron_QA.txt", then  I get

```
2019-05-21 12:01:53 ERROR [admin] ApplicationPageBase - admin: An error occurred while retrieving entity candidates: SPARQL-QUERY: queryStr=SELECT DISTINCT ?lc ?dc ?subj
WHERE { { { { OPTIONAL { ?pLabel <http://www.wikidata.org/prop/direct/P1647>* <http://www.w3.org/2000/01/rdf-schema#label> . }
{ SERVICE wikibase:mwapi { 
bd:serviceParam wikibase:api "EntitySearch" . 
bd:serviceParam wikibase:endpoint "www.wikidata.org" . 
bd:serviceParam wikibase:limit 50 . 
bd:serviceParam mwapi:search "A" . 
bd:serviceParam mwapi:language "en" . 
?subj wikibase:apiOutputItem mwapi:item . 
}
{ ?subj ?pLabel ?lc .
FILTER ( ( REGEX( ?lc, "^A$", "i" ) && LANGMATCHES( LANG( ?lc ), "en" ) ) || ( REGEX( ?lc, "^A$", "i" ) && LANGMATCHES( LANG( ?lc ), "" ) ) ) } } UNION { SERVICE wikibase:mwapi { 
bd:serviceParam wikibase:api "EntitySearch" . 
bd:serviceParam wikibase:endpoint "www.wikidata.org" . 
bd:serviceParam wikibase:limit 50 . 
bd:serviceParam mwapi:search "country The French" . 
bd:serviceParam mwapi:language "en" . 
?subj wikibase:apiOutputItem mwapi:item . 
}
{ ?subj ?pLabel ?lc .
FILTER ( ( REGEX( ?lc, "^country\.\\s+The\\s+French$", "i" ) && LANGMATCHES( LANG( ?lc ), "en" ) ) || ( REGEX( ?lc, "^country\.\\s+The\\s+French$", "i" ) && LANGMATCHES( LANG( ?lc ), "" ) ) ) } } }
FILTER EXISTS { ?subj <http://www.wikidata.org/prop/direct/P31> [ ] .
FILTER NOT EXISTS { ?subj <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q35120> . }
FILTER NOT EXISTS { [ ] <http://www.wikidata.org/prop/direct/P279> ?subj . }
FILTER NOT EXISTS { ?subj <http://www.wikidata.org/prop/direct/P279> [ ] . } } } }
OPTIONAL { { ?subj <http://schema.org/description> ?dc .
FILTER ( LANGMATCHES( LANG( ?dc ), "en" ) ) } UNION { ?subj <http://schema.org/description> ?dc .
FILTER ( LANGMATCHES( LANG( ?dc ), "" ) ) } } }
LIMIT 2000

java.util.concurrent.ExecutionException: org.openrdf.query.MalformedQueryException: Lexical error at line 21, column 34.  Encountered: "." (46), after : "\"^country\\"
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:292)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlQuery(QueryServlet.java:678)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doGet(QueryServlet.java:290)
	at com.bigdata.rdf.sail.webapp.RESTServlet.doGet(RESTServlet.java:240)
	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doGet(MultiTenancyServlet.java:273)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.wikidata.query.rdf.blazegraph.throttling.ThrottlingFilter.doFilter(ThrottlingFilter.java:338)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.wikidata.query.rdf.blazegraph.filters.ClientIPFilter.doFilter(ClientIPFilter.java:43)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openrdf.query.MalformedQueryException: Lexical error at line 21, column 34.  Encountered: "." (46), after : "\"^country\\"
	at com.bigdata.rdf.sail.sparql.Bigdata2ASTSPARQLParser.parseQuery2(Bigdata2ASTSPARQLParser.java:404)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:741)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:695)
	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: com.bigdata.rdf.sail.sparql.ast.TokenMgrError: Lexical error at line 21, column 34.  Encountered: "." (46), after : "\"^country\\"
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilderTokenManager.getNextToken(SyntaxTreeBuilderTokenManager.java:3994)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.jj_ntk(SyntaxTreeBuilder.java:9633)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.UnaryExpression(SyntaxTreeBuilder.java:4337)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.MultiplicativeExpression(SyntaxTreeBuilder.java:4283)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.AdditiveExpression(SyntaxTreeBuilder.java:4189)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.NumericExpression(SyntaxTreeBuilder.java:4185)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.RelationalExpression(SyntaxTreeBuilder.java:4013)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ValueLogical(SyntaxTreeBuilder.java:4009)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ConditionalAndExpression(SyntaxTreeBuilder.java:3973)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ConditionalOrExpression(SyntaxTreeBuilder.java:3937)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Expression(SyntaxTreeBuilder.java:3933)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.RegexExpression(SyntaxTreeBuilder.java:7088)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.StringFunction(SyntaxTreeBuilder.java:5160)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.BuiltInCall(SyntaxTreeBuilder.java:5068)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.PrimaryExpression(SyntaxTreeBuilder.java:4556)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.UnaryExpression(SyntaxTreeBuilder.java:4455)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.MultiplicativeExpression(SyntaxTreeBuilder.java:4283)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.AdditiveExpression(SyntaxTreeBuilder.java:4189)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.NumericExpression(SyntaxTreeBuilder.java:4185)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.RelationalExpression(SyntaxTreeBuilder.java:4013)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ValueLogical(SyntaxTreeBuilder.java:4009)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ConditionalAndExpression(SyntaxTreeBuilder.java:3973)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ConditionalOrExpression(SyntaxTreeBuilder.java:3937)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Expression(SyntaxTreeBuilder.java:3933)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.BrackettedExpression(SyntaxTreeBuilder.java:5030)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.PrimaryExpression(SyntaxTreeBuilder.java:4501)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.UnaryExpression(SyntaxTreeBuilder.java:4455)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.MultiplicativeExpression(SyntaxTreeBuilder.java:4283)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.AdditiveExpression(SyntaxTreeBuilder.java:4189)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.NumericExpression(SyntaxTreeBuilder.java:4185)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.RelationalExpression(SyntaxTreeBuilder.java:4013)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ValueLogical(SyntaxTreeBuilder.java:4009)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ConditionalAndExpression(SyntaxTreeBuilder.java:3973)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.ConditionalOrExpression(SyntaxTreeBuilder.java:3937)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Expression(SyntaxTreeBuilder.java:3933)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.BrackettedExpression(SyntaxTreeBuilder.java:5030)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Constraint(SyntaxTreeBuilder.java:2569)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Filter(SyntaxTreeBuilder.java:2558)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.FilterOrBind(SyntaxTreeBuilder.java:2241)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.BasicGraphPattern(SyntaxTreeBuilder.java:2107)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2030)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1965)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupOrUnionGraphPattern(SyntaxTreeBuilder.java:2447)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPatternNotTriples(SyntaxTreeBuilder.java:2357)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2043)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2052)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1965)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupOrUnionGraphPattern(SyntaxTreeBuilder.java:2447)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupOrUnionGraphPattern(SyntaxTreeBuilder.java:2455)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPatternNotTriples(SyntaxTreeBuilder.java:2357)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2043)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2052)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1965)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupOrUnionGraphPattern(SyntaxTreeBuilder.java:2447)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPatternNotTriples(SyntaxTreeBuilder.java:2357)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2043)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1965)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupOrUnionGraphPattern(SyntaxTreeBuilder.java:2447)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPatternNotTriples(SyntaxTreeBuilder.java:2357)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2043)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1965)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupOrUnionGraphPattern(SyntaxTreeBuilder.java:2447)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPatternNotTriples(SyntaxTreeBuilder.java:2357)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GraphPattern(SyntaxTreeBuilder.java:2043)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.GroupGraphPattern(SyntaxTreeBuilder.java:1965)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.WhereClause(SyntaxTreeBuilder.java:1009)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.SelectQuery(SyntaxTreeBuilder.java:373)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.Query(SyntaxTreeBuilder.java:324)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.QueryContainer(SyntaxTreeBuilder.java:212)
	at com.bigdata.rdf.sail.sparql.ast.SyntaxTreeBuilder.parseQuery(SyntaxTreeBuilder.java:32)
	at com.bigdata.rdf.sail.sparql.Bigdata2ASTSPARQLParser.parseQuery2(Bigdata2ASTSPARQLParser.java:336)
```

The error fills the whole screen and also shows in the dropdown of the feature editor.

**Comment by reckart** [comment]
I have improved the sanitation and conversion into regex queries - could you have another look please?

**Comment by jcklie** [comment]
It works, but I get a lot of 

    2019-05-21 14:39:52 WARN [SYSTEM] ConceptLinkingServiceImpl - Mention sentence could not be determined. Skipping.

**Comment by reckart** [comment]
> 2019-05-21 14:39:52 WARN [SYSTEM] ConceptLinkingServiceImpl - Mention sentence could not be determined. Skipping.

Hm, ok - I guess that would deserve a separate issue then.

**Pull request merged**
