### PR TITLE
#1099 - PDF Editor Documentation

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- add user and developer documentation to PDF editor module

**How to test manually**

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [X] PR updates documentation

### CODE REVIEW

**Comment by wpmp** [comment]
@reckart between which sections should I insert PDF editor documentation?

**Comment by reckart** [comment]
Assuming we get more editors, it doesn't really make sense to cram them all into the annotation page section (I think), so I'd say put them under "advanced functionality".

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
@reckart as this is milestone 0.10.0 now, it should merge into master, right?

**Comment by reckart** [comment]
Aye, I have updated it.

**Comment by reckart** [comment]
Build seems to be failing due to a timeout at Wikidata and due to the YAGO service being offline again :(

**Comment by wpmp** [comment]
Yes, saw it :/
Can't the tests be changed so that they do not run if there is no connection possible?

**Comment by reckart** [comment]
Did that earlier today which is why the pr builds ok again now :)

**Comment by wpmp** [comment]
Nice! :)

**Comment by reckart** [comment]
@UWinch could you please have a look at this one? We need an idea how to best integrate the documentation for the PDF editing mode into the overall documentation. Could you suggest one?

**Comment by UWinch** [comment]
I think I would also keep the pdf documentation in one section like it is now, but add an explanation and link at the beginning of the Annotation section because this is the functionality which is described in the pdf docu e.g.

> The annotation screen allows to view text documents and to annotate them.
In addition to the default annotation view, pdf documents can be viewed and annotated using the PDF-Editor. Please refer to this [link PDF docu] for an explanation on naviaating and annotating in the PDF-view.

Other issues I had when viewing the documentation:

-  I had to change the directory structure for the html to be created correctly e.g.
       src/main/resources/META-INF/asciidoc/user-guide/pdf-editor.adoc
- After this change I had to adapt the links to the images to e.g. 
        image::pdf-panel-top-left.png[align="center"]
- Use something like `PDF-Editor`instead of `User documentation` and `Developer Documentation` for the section headlines .

**Comment by reckart** [comment]
@UWinch would you care to complete the changes you suggested and to commit them?

**Comment by UWinch** [comment]
@reckart @wpmp Done.

**Comment by wpmp** [comment]
@UWinch thanks!

**Pull request merged**
