### PR TITLE
#352 No properties shown in KB UI

### PR DESCRIPTION
**Pull request by naveen2507**
- Properties in KB UI
- Pending: Number of issues after removing the inferencer. Inception
code doesn't identify any obvious relation for SPARQL queries. Need
debugging and changes for most queries.

### CODE REVIEW

**Comment by naveen2507** [comment]
@reckart  Can't have generic queries for in `getStatementsSparql()` anymore.

**Comment by reckart** [comment]
> @reckart Can't have generic queries for in getStatementsSparql() anymore.

Can you be more specific?

**Comment by naveen2507** [comment]
@reckart Now as we don't have the Inferencer anymore, the code doesn't recognize that ObjectProperty, DatatypeProperty, etc are subProperty of Property.  The method getStatementsSparql()  is pretty generic for now and is called for reading concept, instance, and property. But what I see now is we have to cover every aspect in SPARQL queries for reading property as we don't have the support from inferencer anymore.

**Comment by reckart** [comment]
@naveen2507 We could re-enable the inferencer but it would mean that the internal KB can really only pretty small.

**Comment by naveen2507** [comment]
@reckart Let's discuss this. We can get rid of inferencer but it comes with its own pros and cons.

**Comment by naveen2507** [comment]
@reckart I think if we have serious issues with inferencer then we can get rid of that, but in case

**Comment by naveen2507** [comment]
@reckart I think if we have serious issues with working on internal KB's we should get rid of inferencer or we can also explore for some lightweight inferencer for some basics,  or we can ger rid of inferencers and design separate and in depth SPARQL queries. We can have a list of semantic relations,  which we can use as part of our SPARQL query.

**Comment by reckart** [comment]
@naveen2507 I had a look some time back on how the inferencer and native storage interplay in RDF4J and this is what I remember:

1. whenever a triple is added to the KB, the inferencer kicks in
2. every time the inferencer kicks in, it iterates over all triples in the KB and tries to apply its inference roles
3. (on this one I am not entirely sure...) either a) when one or more triple is has been added after applying all inference rule to a given triple, the entire KB is written to disk or b) once all inference rules have passed over all triples the KB is written to disk - I think it is a)
4. if any triple has been added by the inferencer, then go back to step 2

You can easily imagine that this is prohibitive for any but small KBs. RDF4J documentation also warns about using the inferencer. The strategy that they use works ok for KBs that are kept in-memory, but not for on-disk KBs.

Mind this is from memory... I might have missed/forgotten something.

So the options I see are:

* we could choose to use in-memory KBs with the inferencer and only store them to disk from time-to-time. No idea how much main memory use that would incur.
* we could choose to use the disk KB without the inferencer but then we have to write rather complicated queries (the status we have now)
* we could choose to use the disk KB with the inferencer but then we can only have very small internal KBs and for anything non-trivial an external SPARQL service would be required. That would increase pressure for us to implement write support for external KBs (currently they are read-only)
* ... any other suggestions?

**Comment by naveen2507** [comment]
@reckart I dont see any other option for now.  
RDF4J documentation states that : `However, a word of warning: the RDF4J inferencers add a significant performance overhead when adding and removing data to a repository, an overhead that gets progressively worse as the total size of the repository increases. For small to medium-sized datasets it peforms fine, but for larger datasets you are advised not to use it and to switch to alternatives.` 

Have we explored anything on the line of this : 
http://docs.rdf4j.org/programming/#_reasoning_and_validation_suport_with_spin

**Comment by reckart** [comment]
> Have we explored anything on the line of this : http://docs.rdf4j.org/programming/#_reasoning_and_validation_suport_with_spin

Well, we have used the `ForwardChainingRDFSInferencer` before... not sure what you mean?

What do you think about the option of using a memory store and persisting that to disk from time-to-time?

**Comment by reckart** [comment]
@naveen2507 Btw, this issue here confirms my analysis: https://github.com/eclipse/rdf4j/issues/462

**Comment by naveen2507** [comment]
> we could choose to use in-memory KBs with the inferencer and only store them to disk from time-to-time. No idea how much main memory use that would incur.

Yeah i think this would be the most feasible option for us rt now.

**Comment by reckart** [comment]
>> we could choose to use in-memory KBs with the inferencer and only store them to disk from time-to-time. No idea how much main memory use that would incur.
> Yeah i think this would be the most feasible option for us rt now.
I think it would be useful to create a benchmark in the form of a unit test which tries to import WordNet RDF into a native store as well as into a memory store with the inferencer enabled. This should be written without any dependency on INCEpTION in general but can be placed in the KB module. We'd normally mark these tests using `@Ignore` but keep them around in case we need to benchmark different setups.

**Comment by Rentier** [comment]
One can also change the configuration before importing to not use the inferencer, then import, then use the previous configuration. One might need to trigger the inferencer then afterwards once.

**Comment by reckart** [comment]
> One can also change the configuration before importing to not use the inferencer, then import, then use the previous configuration. One might need to trigger the inferencer then afterwards once.

There might be a problem with that when trying to import a **second** RDF file into an existing KB. I'm also not sure how this will work with the repo manager. Can we actually easily change a repo-manager configuration after it has been created? Any idea how this would impact concurrent connections to the KB?

**Comment by Rentier** [comment]
I tried it and it did not complain. The doc (http://docs.rdf4j.org/javadoc/1.0/org/eclipse/rdf4j/repository/manager/RepositoryManager.html#addRepositoryConfig-org.eclipse.rdf4j.repository.config.RepositoryConfig-) says: 

> Adds or updates the configuration of a repository to the manager's system repository. The system repository may already contain a configuration for a repository with the same ID as specified by config, in which case all previous configuration data for that repository will be cleared before the new configuration is added.

The problem with concurrency is already there: what do you do if someone imports a KB and another user edits it at the same time?

**Comment by reckart** [comment]
> The problem with concurrency is already there: what do you do if someone imports a KB and another user edits it at the same time?

The repo supports transactions. So in principle concurrent update should not cause significant problems.

**Comment by naveen2507** [comment]
Issue covered by #394

**Pull request closed without merging**
