### PR TITLE
#1200 - Selected Document Annotation not visible in details

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- document annotation side panel now works as an accordion instead of two separate panels
- the accordion only shows details for the currently selected annotation

**How to test manually**
* open a document in the brat or pdf editor
* create document annotations
* see if everything still works (create, select, delete, update values)

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by wpmp** [comment]
> What is the purpose of the "selection cache"?

When filling a document annotation with data it seems the panel is reloaded, forgetting which annotation was selected and opened.
So when you fill out a value the annotation would close.

**Comment by reckart** [comment]
Before this change, the details and the list were completely separate: one list, on detail panel. So when changes were made to the details, it was necessary/straightforward to simple reload the entire list in order to update the annotation label.

Now, every item in the list has its own private details, so this could probably be solved in a more elegant way. 

However, I would suggest we merge it as is after you added some comments to the places where the selection cache is being used explaining why it is there and what it does.

**Comment by wpmp** [comment]
I think I found a better way than using this selectedCache variable.  
In the `detailPanels` list the existing detail panels are saved.  
Those are now reused, if present, when the rerendering is triggered.  
Otherwise a new detail panel is created.  
This is also necessary because previously with my last solution the list kept growing over time, never being cleared or cleaned.  
How do you like it now?  
Only thing I still don't like is passing the selection panel to the detail panels, but currently I don't see any way around it.

**Comment by wpmp** [comment]
Oh and I noticed that now when creating a new annotation it does not open.
You have to open it manually.
Is this behaviour ok or should it be like before and be opened after it is created?

**Comment by reckart** [comment]
I think it would be convenient for it to be opened when it is created.

**Comment by wpmp** [comment]
Done

**Comment by wpmp** [comment]
@reckart there seems to be an issue with the concept linking package:

```
[WARNING] Used undeclared dependencies found:
[WARNING]    org.dkpro.core:dkpro-core-api-ner-asl:jar:1.11.0:compile
[WARNING]    org.dkpro.core:dkpro-core-api-segmentation-asl:jar:1.11.0:compile
[WARNING] Unused declared dependencies found:
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.segmentation-asl:jar:1.10.0:compile
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.ner-asl:jar:1.10.0:test
```

At least I don't see any other reason for this build to fail

**Comment by reckart** [comment]
I'm looking into the dependency issues...

**Pull request merged**
