### PR TITLE
#1252 Add timeout for external recommender timeout

### PR DESCRIPTION
**Pull request by bjtulinl**
**What's in the PR**
* The default HTTP timeout is not enough for running the external recommender  for e.g. flair.

**How to test manually**
* Use the external recommender to annotate the text and check whether there are timeout errors.

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by jcklie** [comment]
I would not make the client static final, but the time amount, that is the 30 seconds.

**Comment by reckart** [comment]
Please observe the [PR guidelines](https://dkpro.github.io/contributing/) (end of page), e.g. format of commit comments.

**Comment by reckart** [comment]
How about making the timeouts configurable via Spring properties?

**Comment by reckart** [comment]
@jcklie what is the status here?

**Comment by jcklie** [comment]
I would merge it and open another issue to make it configurable. It takes a bit to make it configurable, as recommenders are not spring components.

**Comment by reckart** [comment]
@jcklie you call - proceed as you see fit.

**Comment by jcklie** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
