### PR TITLE
Feature/1358 use bookmarkable links

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Use bookmarkable links in the menubar
- Use bookmarkable links when possible in the dashboard menu

**How to test manually**
* Hover with the mouse over links in the top-main menu bar
* Hover with the mouse over links in a dashboard menu (bookmarkable links show only for pages to which we do not need to pass the current project ID).

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by jcklie** [comment]
@reckart Build error locally as well as on Jenkins:

```
15:54:05 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project inception-recommendation: Compilation failure: Compilation failure:
15:54:05 [ERROR] /srv/home/svc_jenkins/workspace/INCEpTION (GitHub) (PR builder)/git/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java:[21,1] cannot find symbol
15:54:05 [ERROR] symbol:   static selectSingleFsAt
15:54:05 [ERROR] location: class
15:54:05 [ERROR] /srv/home/svc_jenkins/workspace/INCEpTION (GitHub) (PR builder)/git/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java:[625,31] cannot find symbol
15:54:05 [ERROR] symbol:   method selectSingleFsAt(org.apache.uima.cas.CAS,org.apache.uima.cas.Type,int,int)
15:54:05 [ERROR] location: class de.tudarmstadt.ukp.inception.recommendation.service.RecommendationServiceImpl
15:54:05 [ERROR] -> [Help 1]
15:54:05 [ERROR] 
15:54:05 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
15:54:05 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
15:54:05 [ERROR] 
15:54:05 [ERROR] For more information about the errors and possible solutions, please read the following articles:
15:54:05 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
15:54:05 [ERROR] 
15:54:05 [ERROR] After correcting the problems, you can resume the build with the command
15:54:05 [ERROR]   mvn <goals> -rf :inception-recommendation
```

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@jcklie ok, builds again

**Comment by reckart** [comment]
Thanks !

**Pull request merged**
