### PR TITLE
#1677 - New workload management page

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
* ...

**How to test manually**
* ...

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
@christophscheunemann @jcklie I found this unmerged branch on my local checkout - the branch appears to have disappeared from GitHub and instead of this branch, some other branch was merged for #1677. Why do we have two branches?

**Comment by christophscheunemann** [comment]
@reckart This PR was already merged into master by @jcklie. I do not know why this one is here again. As the whole package "inception-workload-dynamic" exists in the master branch, I would say we can simply delete this here.

**Comment by reckart** [comment]
E.g. I do not find the commit https://github.com/inception-project/inception/pull/1759/commits/7380a8270800a865105c73b390afe38439032861 outside of this PR. I searched the commit comments for "Added basic Spring auto-configuration" in the history, but https://github.com/inception-project/inception/pull/1759/commits/7380a8270800a865105c73b390afe38439032861 is the only commit where it shows up. Can you please check what happened here?

**Comment by christophscheunemann** [comment]
@reckart I just checked in the master branch if all of the changes from 7380a82 are there (e.g. the Spring Auto Configuration in "META-INF", the removed "ImagePanel", implementation of "DynamicWorkloadManagerAutoConfiguration", Autowired constructor for WorkloadPageMenuItem, changes in the TableContentProvider etc. ). 
Everything is available in the master branch.

**Comment by jcklie** [comment]
@reckart Can we close this PR?

**Comment by reckart** [comment]
This was merged via squash which is why the branch appeared as an unmerged orphan in my clone.

Yes, let's close it. Let's please try to avoid squashing as much as possible in the future.

**Pull request closed without merging**
