### PR TITLE
#336 - NamedEntityLinker broken

### PR DESCRIPTION
**Pull request by rcffc**
Added a flag which indicates recommenders that should be skipped during SelectionTask (Evaluation), e.g. NamedEntityLinker

### CODE REVIEW

**Comment by reckart** [comment]
@rcffc Doesn't seem to work... I get lots of these in the logs:

```
2018-07-05 16:28:15 WARN [SYSTEM] SPARQLProtocolSession - Server reports problem: Virtuoso 37000 Error SP030: SPARQL compiler, line 23: syntax error at 'UNION' before 'SELECT'

SPARQL query:
define sql:big-data-const 0 DEFINE input:inference 'instances'
PREFIX e:<http://www.wikidata.org/entity/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX base:<http://www.wikidata.org/ontology#>
PREFIX schema: <http://schema.org/>
SELECT DISTINCT ?e2 ?altLabel ?label ?description WHERE
{
  {
SELECT DISTINCT ?e2 ?description WHERE
    {
     VALUES ?labelpredicate {rdfs:label skos:altLabel}
      GRAPH <http://wikidata.org/terms>
      {
        ?e2 ?labelpredicate '"mit"' @en .
        OPTIONAL
        {
          ?e2 <http://schema.org/description> ?description.
          FILTER ( lang(?description) = "en" )
        }
      }
    }
    UNION
SELECT DISTINCT ?e2 ?altLabel ?description WHERE
    {
      VALUES ?labelpredicate {rdfs:label skos:altLabel}
      GRAPH <http://wikidata.org/terms>
      {
        ?e2 ?labelpredicate ?altLabel.
        ?altLabel bif:contains '"mit"'. 
        OPTIONAL
        {
          ?e2 <http://schema.org/description> ?description.
          FILTER ( lang(?description) = "en" )
        }
      }
    }
LIMIT 2500
  }
  FILTER EXISTS { GRAPH <http://wikidata.org/statements> { ?e2 ?p ?v }}
  FILTER NOT EXISTS 
  {
    VALUES ?topic {e:Q17442446 e:Q14204246 e:Q4167836 e:Q4167410 e:Q13406463 e:Q11266439 e:Q17633526 e:Q11753321}
    GRAPH <http://wikidata.org/instances> {?e2 rdf:type ?topic}
  }
  BIND (STRLEN(?altLabel) as ?len)
  {
    GRAPH <http://wikidata.org/terms> { ?e2 rdfs:label ?label. }
    FILTER ( lang(?label) = "en" )
  }
}
```

**Comment by rcffc** [comment]
This should be a problem of issue #306, not #336

**Comment by reckart** [comment]
Odd because I was pretty sure that I checked out and tested `bugfix/336-named-entity-linker-broken`.

**Comment by reckart** [comment]
I will try again.

**Pull request merged**
