### PR TITLE
#420 Cannot delete KB instance

### PR DESCRIPTION
**Pull request by naveen2507**
When deleting instances in the KB view, it throws an exception:

### CODE REVIEW

**Comment by Rentier** [comment]
It works, but it logs 
```2018-07-26 16:34:48 WARN [admin] XmlPartialPageUpdate - Component '[ContentPanel [Component id = content]]' with markupid: 'id138' not rendered because it was already removed from page
```

**Comment by naveen2507** [comment]
@Rentier It logs because of the instance component which is being selected is deleted and it changes the selection to the concept. I think for now, its not an issue for now. I will look into this when i change the UI for instance "concept mentions" .

@Rentier  the PR can be approved.

**Comment by naveen2507** [comment]
@Rentier changed the base to 0.4.x

**Comment by Rentier** [comment]
Why are there so many commits in here?

**Comment by naveen2507** [comment]
@Rentier Opening another pull request.

**Pull request closed without merging**
