### PR TITLE
Feature/372 redesign layout of search page

### LINKED ISSUE #372: Redesign layout of search page
**Is your feature request related to a problem? Please describe.**
Current initial layout is very basic.

**Describe the solution you'd like**
Include document title, confidence score, list of snippets for every result.

### LINKED ISSUE #374: Show which documents are already imported
**Is your feature request related to a problem? Please describe.**
Currently, the list of results does not differentiate between documents not imported and already imported.

**Describe the solution you'd like**
Add a column or sign to indicate which documents have already been imported into the current selected project.

### LINKED ISSUE #375: Open external document in a new page
**Is your feature request related to a problem? Please describe.**
Currently, the external document is shown in a popup.

**Describe the solution you'd like**
Open the document in a new page instead of popup. Use a visible URL with page parameters for the document.

### PR DESCRIPTION
**Pull request by az79nefy**
* Redesign of the external search page layout (resolves #372 )
* Import document by button + import status changes dynamically (resolves #374 )
* Document opens as new window instead of popup (resolves #375 )

How to test: 
- Access page through the "Search" menu button and make a search query
- Open the text of a document
- Import a document

### CODE REVIEW

**Comment by az79nefy** [comment]
This pull request will:
- resolve #372
- resolve #374 
- resolve #375

**Comment by az79nefy** [comment]
How to test:

- Access page through the "Search" menu button and make a search query
- Open the text of a document
- Import a document

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@Rentier you need to add `external-search.enabled=true` to your `settings.properties` file to enable external search.

**Comment by Rentier** [comment]
@az79nefy `[WARNING] Used undeclared dependencies found:
[WARNING]    org.springframework:spring-beans:jar:5.1.1.RELEASE:compile`

**Pull request merged**
