### PR TITLE
#413 - Release 0.4.1

### PR DESCRIPTION
**Pull request by Rentier**
- Update Webanno version

### CODE REVIEW

**Comment by reckart** [comment]
How about running the whole release on this branch and then merge it afterwards?

**Comment by Rentier** [comment]
I can do that.

**Comment by Rentier** [comment]
The build runs locally through for me, in the Jenkins log file I cannot spot the error.

**Comment by Rentier** [comment]
`Failed to deploy artifacts: Could not transfer artifact de.tudarmstadt.ukp.inception.app:inception-app:pom:0.4.1 from/to ukp-oss (https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-releases-local): Failed to transfer file: https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-releases-local/de/tudarmstadt/ukp/inception/app/inception-app/0.4.1/inception-app-0.4.1.pom. Return code is: 401, ReasonPhrase: Unauthorized.`

**Comment by reckart** [comment]
The Jenkins job is set up to deploy to a SNAPSHOT repo - it will not accept release versions. If that is the only problem, no problem. In any case, once the full release cycle has been run and the version has been updated to 0.4.2-SNAPSHOT, it should get green again.

**Comment by reckart** [comment]
@Rentier mind that the build process does not automatically sign the standalone JAR file - please do that manually before uploading the JAR and the signature file to the GitHub release.

**Comment by Rentier** [comment]
@reckart Can we talk on Gitter?

**Pull request merged**
