### PR TITLE
#1239 - Support recommendation of simple relations

### PR DESCRIPTION
**Pull request by jcklie**
# What's in the PR
- Rename String Recommender package
- Start simple projecting relation recommender
- Renamed `AnnotationSuggestion` to `SpanSuggestion`
- Introduced `AnnotationSuggestion` interface on top of `AnnotationSuggestion_ImplBase`

# How to test manually  

_**This PR removes columns from the database, switching to another branch after running this might be difficult before it is merged!**_

* Create a new project and upload a document
* Define a new span layer with a String feature 
* Add a relation layer ontop of that previously created layer and add a relation layer
* Add a string relation recommender on that relation layer
* Mark a span "a" and a span "b" in the same sentence
* Draw a relation between them and give it a label
* In another sentence, also mark a span "a" and a span "b" in the same sentence
* It should recommend the label you defined for the first sentence

* Check that active learning and recommender still work
* Check that existing string recommender in other projects still work

**Automatic testing**
* [x] PR includes unit tests

**Documentation**
* [x] PR updates documentation

**Things missing:**

- [x]  Check active learning
- [x] Write unit tests
- [x] Sorting by confidence
- [x] Max suggestions
- [x] Rejection hiding and learning record
- [x] Lazy details (confidence, label)
- [x] Several recommender grouping

### CODE REVIEW

**Comment by jcklie** [comment]
@reckart This is the relation recommendation PR.

**Comment by reckart** [comment]
Lots of conflicts...

**Comment by jcklie** [comment]
I can have a quick look today why that is, I assume it is just because of renaming stuff.

**Comment by reckart** [comment]
It would be useful to have some checklist in the PR telling what is done and what still needs to be done.

**Comment by jcklie** [comment]
This PR implements a  simple relation recommender. It does not contain code for creating `AnnotationSuggestion` pendants for relations and rendering yet. I thought about it and am not sure how to best refactor `AnnotationSuggestion` to also handle relations, coreference and the like. We can have an abstract `AnnotationSuggestion` class and then a `SpanSuggestion` and `CoreferenceSuggestion` and `RelationSuggestion`. We would e.g. move `begin`, `end`, `coveredText` from `AnnotationSuggestion` to `SpanSuggestion`. We have to think how active learning should work with relations. Later, we have to think about how we can build relation recommendations based on other span recommendations.

**Comment by jcklie** [comment]
I wanted to call the base AnnotationSuggestion and the other ones like SpanSuggestion or so.

**Comment by reckart** [comment]
Refactoring is in progress. Be sure there will be more renaming :)

**Comment by reckart** [comment]
If we rename too much now, we'll have issues merging in changes from master.

**Comment by jcklie** [comment]
I have trust in your judgement.

**Comment by reckart** [comment]
@jcklie I made the changes we discussed. I'll approve the changes so you can have another look and eventually merge this as the first PR towards relation recommendation.

**Comment by UWinch** [comment]
Jenkins, can you test this please?

**Comment by jcklie** [comment]
Currently I do not know how to add relation suggestions to the learning log, as that wants begin/end offsets. I could save source and target XMI ids like I do in other places, but these are not persistent and therefore we cannot save them in the DB.

**Comment by reckart** [comment]
These were the two things I noted when going through the changes:

* upsert relation should create new relation if stacking is allowed
* make "adjuct feature" in relation traits configurable - or maybe use all the label features

@jcklie mentioned that the relation recommender is probably not enabled for stacking layers anyway and for the other thing, we have an issue now as far as I saw.

**Comment by jcklie** [comment]
The adjunct feature is configurable now and I added documetnation

**Review by UWinch — COMMENTED** [review]
Does not work for me yet, I'm not getting any recommendations. I see the following error in the logs, maybe this has something to do with it:

```

2021-03-29 13:16:34 ERROR [SYSTEM] SelectionTask - [admin][[NERel@relation] String Matcher for relations]: Failed
java.lang.NullPointerException: null
	at de.tudarmstadt.ukp.inception.recommendation.tasks.SelectionTask.run(SelectionTask.java:200) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```

I also get a `SQLSyntaxErrorException: Unknown column 'offsetCharacterBegin' in 'where clause'` when I accept recommendations of normal string matchers.

**Comment by jcklie** [comment]
@UWinch Thank you for the feedback,  incorporated it. I cannot reproduce the NPE, can you check in your database whether the db changes were applied correctly?

**Comment by jcklie** [comment]
@UWinch I think I found the error, I will fix it asap.

**Comment by jcklie** [comment]
@UWinch I fixed it, you need to annotate enough if you decide to not skip evaluation.

**Comment by UWinch** [comment]
I'm now getting a `Error: SQLIntegrityConstraintViolationException: Column 'suggestionType' cannot be null` when accepting recommendations from normal Stringmatchers.

The relation recommenders work well for me, the robot is the cutest :robot: However, suggestions seem to be shown in double
rel-rec

**Pull request merged**
