### PR TITLE
Feature/244 extend scope search annotated kb identifier

### PR DESCRIPTION
**Pull request by naveen2507**
- [x] Search for a specific instance, plus its class and all its super classes.

- [x] KBSI : Add method to get , if an IRI is an instance or class

### CODE REVIEW

**Comment by Rentier** [comment]
Why does this have so many commits?

**Comment by naveen2507** [comment]
@Rentier the issue is dependent on changes from PR #51

**Comment by naveen2507** [comment]
@reckart  @betoboullosa to can you review this PR for 0.5.0 (PR is dependent on PR #51 , so first #51 needs to be done)

**Comment by naveen2507** [comment]
PR dependent on #51

**Comment by reckart** [comment]
@naveen2507 This is the PR which includes the indexing of superclasses, right? As far as I can see, it contains many commits from #50, not only selective cherry-picked code.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
The items in the dropdown of the `identifier` feature seem not to be ordered and are not filtered by the text entered into the input field.

**Comment by naveen2507** [comment]
> The items in the dropdown of the identifier feature seem not to be ordered and are not filtered by the text entered into the input field.

Are u referring to the Annotation Page for the list of identifiers? Its not part of the this PR.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
