### PR TITLE
fix: improve feature form tab navigation

### PR DESCRIPTION
**Pull request by tpluscode**
I found form fields backed by a KB a little annoying because they render an additional button to explore the KB, and yet another when a value is selected. This disrupts the expected TAB navigation through the form. Not only a single TAB does not move from the previous field, a varying number of TAB are required depending on the field state.

https://github.com/user-attachments/assets/80893143-6bc0-448a-a482-aa111d2b65b3

In this PR, I added `tabindex="-1"` so that the additional link buttons are skipped when navigating though the form with a keyboard.

### CODE REVIEW

**Comment by reckart** [comment]
Nice. If you want this to go in the the next bugfix release, please branch the fix off the `release/33.x` branch and target that branch in the PR. Otherwise, it will only go into 34.x.

**Comment by tpluscode** [comment]
All right. Rebased, force-pushed, PR updated

**Comment by reckart** [comment]
GitHub seems to have trouble building this branch. I'll try again later.

**Comment by tpluscode** [comment]
Fails to check out, what? Does it work for you locally?

**Comment by tpluscode** [comment]
I will recreate the PR if problem persists

**Comment by reckart** [comment]
See the GitHub action logs. For some reason, the git binary returns an error code. I assume it may be a temporary problem on the GitHub action servers...

**Comment by reckart** [comment]
PR still fails:

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/patch-1*:refs/remotes/origin/patch-1* +refs/tags/patch-1*:refs/tags/patch-1*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 10 seconds before trying again
```

**Comment by tpluscode** [comment]
What does that even mean? I don't see anything unusual about your workflow or this PR 🤔

**Comment by reckart** [comment]
I have no idea - I have never seen this either.

**Comment by reckart** [comment]
Superseded by https://github.com/inception-project/inception/pull/5041 due to issues with the GH action.

**Comment by reckart** [comment]
Hit the same issue now on another PR - opened a discussion item with GitHub support: https://github.com/orgs/community/discussions/138018

**Comment by tpluscode** [comment]
Very curious. Thanks for the link

**Pull request closed without merging**
