### PR TITLE
#687 - Wine Ontology missing from packaged version

### PR DESCRIPTION
**Pull request by MdeBoer95**
**What's in the PR** 
* read kb in classpath as inputstream instead of file 
* move function to support module

**How to test manually**
* create a new kb in the wizard and import wine kb (needs to be tested in packaged version)

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by Rentier** [comment]
@MdeBoer95 How do I get the packaged version?

**Comment by MdeBoer95** [comment]
@Rentier I mean running the application via the jar.

**Comment by Rentier** [comment]
When I run the `./inception-app-standalone-0.7.0-SNAPSHOT.jar`, then I get on accessing

`Caused by: java.util.MissingResourceException: Unable to find property: 'PermissionLevel.manager' for component: project:0:role [class=de.tudarmstadt.ukp.inception.ui.core.dashboard.ProjectsOverviewPage$2]. Locale: null, style: null`

@MdeBoer95 @reckart Is it me or is it this PR?

**Comment by reckart** [comment]
@Rentier looks like you are using a wrong WebAnno version.

**Comment by Rentier** [comment]
I tried it with webanno master and newest PR, still I get this error when logging in.

**Comment by Rentier** [comment]
I imported the WIne Profile and did not change anything else, but it is still not there. I used the standalone jar.

**Comment by MdeBoer95** [comment]
@Rentier so no error but an empty KB? Did you click on the "add" button when importing the wine kb?

**Comment by reckart** [comment]
@MdeBoer95 there is a conflict with the KB panel refactoring. Could you have a look at it please?

**Pull request merged**
