### PR TITLE
[WIP] 785 log external search

### LINKED ISSUE #785: Event Logging for External Search
We would like to have event logs of external searches performed by the users. The log should include the time the search was performed, the user performing the search, the query performed.

### PR DESCRIPTION
**Pull request by rgabbard**
**What's in the PR**
* This PR adds logging of external searches made by users. Closes #785 .

**How to test manually**
1. Create and activate a project configured to use external search.
2. From the main Inception page, click “Search”.
3. Type a query into the search box, say 'christmas`, and hit “Search”.
4. Confirm that there is a corresponding console log for `ExternalSearchQueryEvent`  that looks something like:
`2018-12-14 11:26:15 INFO [admin] EventRepositoryImpl - LoggedEvent [created=Fri Dec 14 11:26:15 PST 2018, event=ExternalSearchQueryEvent, user=admin, project=1, annotator=admin, details={"query":"christmas"}]`
Confirm that all the fields are correct.
5. Open the database to check in the `Inception` database, table `logged_event` to make sure the search is logged. Below are commands for MySQL.
5.1 `mysql --user=root --password` to log into database as root.
5.2 `use inception` to switch to database for inception.
5.3 `SELECT * FROM logged_event ORDER BY created ASEC LIMIT 1` to see the last created log. Confirm that it is an ExternalSearchQueryEvent for `event` column and that `user`, `project` and `details` (query string) are correct.

**Automatic testing**
* [ ] PR includes unit tests (not immediately obvious how to unit test it; current search logging doesn't have tests as a model)

**Documentation**
* [ ] PR updates documentation (this probably doesn't need to be documented, unless we have a list somewhere of all logged events)

### CODE REVIEW

**Comment by shinyichen** [comment]
#How to test manually
Perform external searches. There should be corresponding console log that looks something like:
`2018-12-14 11:26:15 INFO [admin] EventRepositoryImpl - LoggedEvent [created=Fri Dec 14 11:26:15 PST 2018, event=ExternalSearchQueryEvent, user=admin, project=1, annotator=admin, details={"query":"christmas"}]`
Then check in the `Inception` database table `logged_event` to make sure the searches are logged.

**Comment by Rentier** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@shinyichen We let Jenkins monitor the dependency footprint of our modules in order to avoid surprises when resolving dependency versions as well as to avoid having unused dependencies bloat the application.

Jenkins tells us that the PR introduces a new used dependency to the external search module which has not yet been declared in the POM - and therefore Jenkins fails the build:

```
[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (default) @ inception-external-search-core ---

[WARNING] Used undeclared dependencies found:
[WARNING]    de.tudarmstadt.ukp.clarin.webanno:webanno-support:jar:3.5.0-SNAPSHOT:compile
```

**Comment by reckart** [comment]
@rgabbard @shinyichen the new files lack a license header. Best copy one from another Java file.

```
[WARNING] Files with unapproved licenses:
  /home/svc_jenkins/workspace/INCEpTION (GitHub) (PR builder)/git/inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/event/ExternalSearchQueryEvent.java
  /home/svc_jenkins/workspace/INCEpTION (GitHub) (PR builder)/git/inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/log/ExternalSearchQueryEventAdapter.java
```

**Comment by rgabbard** [comment]
@reckart : [The Jenkins build](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/INCEpTION%20(GitHub)%20(PR%20builder)/1934/) failed for unclear reasons.  If I click "Test Result (1 failure / +1)" I get:

```
de.tudarmstadt.ukp.inception.log.EventRepositoryImplTest.initializationError

Error message: No runnable methods

Stack Trace

java.lang.Exception: no runnable methods

Failing for the last 12 builds since #1923 [which is a different PR, concerning a learning curve diagram]
```

But this PR doesn't touch that code.  I am also confused about where this test is located, since `inception-log` has no `src/test` hierarchy and searching the repository for `EventRepositoryImplTest` on GitHub didn't turn anything up.

Also, at the end of the main build log, I see:

```
Build step 'Dependency analysis' marked build as failure
```

but if I search through the log, none of the runs of the dependency plugin produced any errors.

**Comment by reckart** [comment]
@rgabbard yes - I was just looking at that as well... I'll try a local build to see if that tells me more.

**Comment by reckart** [comment]
@rgabbard my best guess at this moment is that Jenkins somehow mixed up the job results from a PR job running for #708 (which includes `EventRepositoryImplTest`) and a PR job running for this PR...

**Comment by reckart** [comment]
@rgabbard I'm about to merge this. Are you ok with the state of the PR (i.e. the license headers that I added)? 

I'd tend towards doing a squash merge since that way I don't have the problem of fixing those commit messages in the PR which do not follow our conventions - but it will loose individual commit information.

**Comment by rgabbard** [comment]
@reckart : Yes, the license headers are fine and I agree a squash merge seems best here.

**Comment by reckart** [comment]
@rgabbard Mind if I add you and @shinyichen to the contributors file as part of the PR?

**Comment by rgabbard** [comment]
@reckart : Sure, go ahead.

**Pull request merged**
