### PR TITLE
#1982 - Remove concept of "current project" from the session

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Remove the current project session metadata
- Introduce new ProjectPageBase, ProjectContext and ProjectMenuItem as a replacement
- Use bookmarkable links in the project dashboard
- Adjust URL scheme for project pages
- Merged INCEpTION's overrides for some menu items into the proper modules
- Replaced some explicit page mounts in WicketApplicationBase with Wicket Spring annotation-driven configuration

**How to test manually**
* No specific test procedure - change essentially affects all pages, so any of them could have broken
* Navigation between pages is probably most affected
* Things that could be tried is entering IDs for document and project that do not match (e.g. try using ID of project A but the document ID of some document from project B)
* Could also try to open a document / project for which the user does not have permissions

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

**Issues found**
* [x] creating a new project does not work anymore
* [x] invite link does not work anymore
* [x] message when accessing Annotation Page as annotator (only): `ERROR [bob] ApplicationPageBase - bob: You have no permission to access project [16]`
* [x] opening a document after importing it via external search does not work anymore
* [x] importing project does not update project list (needs reload)
* [x] cancelling a "open document" dialog on the annotation or curation page goes back to the project overview instead of the project dashboard
* (**cannot reproduce**) evaluation metrics for recommenders (sidebar) seem to not work anymore (always zero)
* (**cannot reproduce**) errors for permissions when saving preferences on Annotation Page

### CODE REVIEW

**Review by UWinch — COMMENTED** [review]
Some problems I found:

- creating a new project does not work anymore
- invite link does not work anymore
- message when accessing Annotation Page as annotator (only): `ERROR [bob] ApplicationPageBase - bob: You have no permission to access project [16]`
- errors for permissions when saving preferences on Annotation Page
- importing project does not update project list (needs reload)
- evaluation metrics for recommenders (sidebar) seem to not work anymore (always zero) 
- opening a document after importing it via external search does not work anymore

**Comment by reckart** [comment]
> errors for permissions when saving preferences on Annotation Page

I believe the fix for allowing an annotator to open a document for annotation may also have fixed this one - at least I don't seem to be able to reproduce it.

**Comment by reckart** [comment]
I believe this broke when the `ProjectImportPanel` was refactored so it could be reused on the project settings page as well as on the project overview page...

**Comment by reckart** [comment]
> evaluation metrics for recommenders (sidebar) seem to not work anymore (always zero)

@UWinch I have at least one project where metrics show up. Could you please look at this further any if the issue persists for you open another issue - optimally with a project attached that highlights the issue?

Screenshot 2021-02-11 at 20 58 58

**Pull request merged**
