### PR TITLE
Feature/1621 upgrade to bootstrap 4

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
* Upgrades to Bootstrap 4
* Requires Java 11 (see [upstream issue](https://github.com/l0rdn1kk0n/wicket-webjars/issues/62))

**How to test manually**
* Use UI and functionality of the application

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

*Prerequisites*
* https://github.com/webanno/webanno/pull/1619

### CODE REVIEW

**Comment by UWinch** [comment]
The tutorial does no longer work, I'll look into the problem.

**Comment by reckart** [comment]
> When editing the knowledge base, the save/delete buttons for statements have shifted:

The buttons are placed right of the inputs *if* the screen is wide enough. Otherwise they wrap. The thing is that the KB page is pretty crowded and there is little space.

> There also seems to now be too little space for images in metadata annotations

Thanks. It seems to be an issue with the metadata sidebar in general - if a metadata annotation has a very long label, it pushes content out. I'm sure this is fixable, but with a quick look at it, I couldn't fix it yet.

**Comment by reckart** [comment]
Jenkins can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by jcklie** [comment]
Looks good so far. Some minor comments (no need to fix if you disagree):

image

I find not using h5 here looks better.

The sidebar looks in the dashboard looks a bit out of place now.

From my side, this can be merged.

**Comment by reckart** [comment]
@jcklie feel free to adjust the Project Overview Page looks.

I don't understand the comment about the sidebar.

**Comment by jcklie** [comment]
I would expect the sidebar to look like this: 

https://getbootstrap.com/docs/4.1/examples/dashboard/ 

It is not so important though

**Pull request merged**
