### PR TITLE
#870 - IRI info for IRI-valued statements

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Factor IRI badge out into a re-usable class
- Add IRI badge to IRI-value statements in presentation mode
- Move IRI badge to the front of property labels in the statement group so they are all nicely aligned
- Optimized the loading of the KBObject in the IRI Value presenter to avoid unnecessary KB queries

**Note:** Made this a 0.7.1 feature since it is small and very useful.

**How to test manually**
- Open KB
- Look for IRI-valued statments
- Click on IRI badge to see if IRI tooltip appears and shows the expected value

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
Review anybody? I'm afraid that having provided the PR, I cannot review it myself.

**Comment by MdeBoer95** [comment]
Just out of curiosity. Is there any benefit from checking against ```null``` compared to checking if an Optional value ```isPresent()```? (see changes in ```IRIValuePresenter```)

**Comment by reckart** [comment]
> Just out of curiosity. Is there any benefit from checking against null compared to checking if an Optional value isPresent()? (see changes in IRIValuePresenter)

Puh, maybe not. When working at the Wicket layer, I'm used to working with serializable objects (Optional is not serializable) and with the fact that wicket components/models can usually deal with `null` but have no idea how to treat an `Optional`. I'd have to review in detail again to figure out whether in this particular case it would be possible to use `Optional` and to which extent.

**Comment by reckart** [comment]
@MdeBoer95  Thanks for the review :)

**Pull request merged**
