### PR TITLE
#1085 - Creating Stacking Spans in PDF editor

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
* Enables the creation of stacking spans in the pdf editor

**How to test manually**
1. Open a document in the PDF editor
2. Create a span
3. Create another span that shadows the previously created span

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by wpmp** [comment]
This PR is based on #1230
It is ready for a review after #1230 was merged

**Comment by UWinch** [comment]
This does not work for me. I tried with custom layers:
* span, token-level, any overlap, crossing sentences
* span, char-level, only stacking
* span, single-token, stacking only.

Maybe I'm doing something wrong? I'm clicking and dragging to create the first annotation and then try to click into the annotation again but cannot select anything inside it. However, when I annotate stacked annotations in the brat-view, these stacked annotations do show up in the pdf-view.

**Comment by wpmp** [comment]
@UWinch which browser do you use?

**Comment by reckart** [comment]
@UWinch if you are using Eclipse, make sure you follow these steps to ensure you have the latest JS code for the PDF module:

* switch to the PR branch
* select all inception modules
* right click -> Maven Update (necessary to trigger a rebuild of the JS code in the pdf module)
* in the browser on the annotation page with the PDF editor activated, clear cache and force-reload to ensure that the browser uses the latest JS code

**Comment by wpmp** [comment]
Nice :)

**Pull request merged**
