### PR TITLE
#1883 Clearer label in recommendation sidebar

### PR DESCRIPTION
**Pull request by nkolmar**
**What's in the PR**
* rename "Max. suggestions" label to "Max. suggestions per token"
* adapt user guide to this change and previous changes on the recommendation sidebar

**How to test manually**
* Start INCEpTION and open the recommendation sidebar
* Build the user documentation and read the section "Recommendation Sidebar"

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Review by reckart — CHANGES_REQUESTED** [review]
As discussed, "Max. suggestions per token" doesn't really capture what happens either. It is rather "Top n annotations from all recommenders for a given span and given feature".  It was suggested to add an explanatory tooltip or a help link directly into the documentation as we e.g. also have them on the Layers pane in the project settings.

**Comment by nkolmar** [comment]
@reckart I undid the label renaming and added a link to the documentation as discussed.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Review by reckart — APPROVED** [review]

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
