### PR TITLE
#1492 - New style for document metadata sidebar

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- apply accordion style to the document annotation list
- if no feature preview is available show nothing instead of the document annotation label

**How to test manually**
* Play around with the document metadata sidebar

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
I'd suggest to move the arrow to the left side. 

When I open the sidebar, currently all arrows point down. When I click on an arrow, the entry opens. When I click on it again, it closes and the arrow points up. I guess it should also point up at the star then.

Actually, instead of having the arrow pointing up, I think it should be pointing to the right - or alternatively consider using a "+" and "-" instead of the arrows.

**Comment by wpmp** [comment]
Done.

It should have shown the angle down when closed and up when opened, I must have broken it at some point and didn't notice it then.
But this should work correctly now.

**Comment by wpmp** [comment]
Need to check something before the next review

**Comment by wpmp** [comment]
Ok, now it's ready.

**Pull request merged**
