### PR TITLE
Bugfix/1825 duplicates in search

### PR DESCRIPTION
**Pull request by UWinch**
**What's in the PR**
- deindex, index in one
- do not shutdown scheduler
- only search with searchmanager to stay up to date

**How to test manually**
* Make sure that during searches no duplicates are found
* Test a few times because before the fix the bug was still found sometimes after a few successful searches

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by UWinch** [comment]
Jenkins, can you test this please?

**Comment by jcklie** [comment]
Jenkins has build errors

**Review by jcklie — APPROVED** [review]
I clicked around a bit in the KB wine example, created and deleted things but never saw duplicates

**Comment by reckart** [comment]
@UWinch the PR is still marked as a draft - anything left to do here?

**Pull request merged**
