### PR TITLE
Feature/271 add annotation feature to learning history database

### PR DESCRIPTION
**Pull request by matchlesswei**
- add AnnotationFeature in learning_record 
- set AnnotationFeature when AL sidebar or Recommendation module writes the record.
- change liquibase-log and set foreign key constraints

### CODE REVIEW

**Comment by reckart** [comment]
@matchlesswei conflicts need to be resolved.

**Comment by reckart** [comment]
@matchlesswei can you please resolve the conflicts?

**Comment by matchlesswei** [comment]
@reckart yes, I'm also waiting for the merge of the other PR. Because after the merge, new conflicts will arise.

**Comment by matchlesswei** [comment]
I haven't tested after resolving conflicts because of #343 .

**Comment by matchlesswei** [comment]
This PR can also be merged after PR#294 is merged.

**Comment by reckart** [comment]
@matchlesswei could you please have a look at the conflict?

**Comment by matchlesswei** [comment]
I have already merged this PR into #229. And #229 is merged 👍. So can I close this PR?

**Comment by reckart** [comment]
Ok

**Comment by reckart** [comment]
Well, since the conflict is resolve, we can also just merge it :)

**Pull request merged**
