### PR TITLE
#2316 - Fix typos in user guide

### PR DESCRIPTION
**Pull request by Falko1**
**What's in the PR**
-only removed some typos

**How to test manually**
* read the documentation

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
Since GitHub supports "draft" PRs now , we do not need the WIP label anymore.

**Comment by jcklie** [comment]
The Table of Contents" sidebar on the left moves from "Project Settings" to "Structure of an Annotation Project" way too early, i.e. already in the "Tagsets" subsection of "Project Settings".

@reckart Do you have an idea why that could be? I see many pictures in that section, maybe that is what is throwing tocify off. That is sadly not maintained anymore, last commit around 2013 from what I saw.

**Comment by reckart** [comment]
Does it work when you do a plain asciidoc render without tocify?

**Comment by reckart** [comment]
The sidebar is generated by asciidoc. Tocify goes over the content of the sidebar to make it nice. It doesn't go over the entire document, so nothing that is outside the sidebar should be able to affect it.

**Comment by jcklie** [comment]
I thought the tocify is what makes the sidebar automatically collapsing (in this case too early). Removing tocify creates the non-automatic sidebar which cannot have this error.

**Comment by reckart** [comment]
Ah. Then could it be that an anchor name is used twice (copy-paste bug)?

**Comment by jcklie** [comment]
I dont see any duplicate anchors or ids when I look at the HTML, there is nothing special in the content when it switches. I dont think it is a blocker though.

**Comment by jcklie** [comment]
We also should remove the webanno part from the INCEPTION Intellij dev  guide  I guess.

**Review by jcklie — APPROVED** [review]
Looks very good to me, especially making the links open in a new window and the new screenshots!

**Comment by jcklie** [comment]
Jenkins, can you test this please?

**Comment by UWinch** [comment]
Looks really good, thanks. One quick remark: in the getting started guide we still say that Java 8 or higher is required. I think it should be 11 or higher now.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by jcklie** [comment]
Jenkins, can you test this please?

**Pull request merged**
