### PR TITLE
#1089 - PDF Editor Viewport undefined

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Avoid accessing the first rendered page if it has not been rendered yet

**How to test manually**
* Basically open and PDF - for me the error described in the issue happened *always* when opening a PDF document after coming from the dashboard page

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
I found it pretty easy to debug. I set the JS debugger in the browser to stop on any exception and then waited until this particular exception turned up. Then I inspected the stack trace in the JS debugger.

Are you sure you rebuilt the JS code and cleared your browser cache before testing?

**Comment by wpmp** [comment]
Yes, I do so too, however there are many usages of `viewport` and as the error gives no clue where it comes from there are many possibilities I think.

I am, I can see the additions you made in the JavaScript files.
I made a clean install and force reloaded in the browser.
For me it never happens immediately as it did for you, it always occurs after opening some PDFs in the PDF editor.

**Comment by wpmp** [comment]
Oh wait, I didn't debug like you did.. Nevermind, I will try like this.

**Comment by reckart** [comment]
> Yes, I do so too, however there are many usages of viewport and as the error gives no clue where it comes from there are many possibilities I think.

That is why I set a breakpoint on exceptions. It makes the debugger stop whenever an exception is thrown and in this way I can locate the code from which the exception originates.

**Comment by wpmp** [comment]
Yes, sorry, was too quick on this.
For me it happens in `pdfanno/src/core/src/render/appendChild.js` on line 29.
Will you have a look at it?
Otherwise I maybe can further look into this tomorrow.

**Comment by reckart** [comment]
From a quick look I would say the method should be made to return if `window.PDFView.pdfViewer.getPageView(0) === undefined`. But if I cannot reproduce it, it is difficult to fix it.

**Comment by reckart** [comment]
An alternative to changing all the code which fetches the viewport would probably be to defer the loading of the annotations until a viewport is actually available, e.g. by listening to the "pagerendered" event...

**Comment by wpmp** [comment]
> From a quick look I would say the method should be made to return if `window.PDFView.pdfViewer.getPageView(0) === undefined`. But if I cannot reproduce it, it is difficult to fix it.

Well, that's true :)
I'll try to work on this tomorrow.

> An alternative to changing all the code which fetches the viewport would probably be to defer the loading of the annotations until a viewport is actually available, e.g. by listening to the "pagerendered" event...

This is probably the best approach.
Do we still keep your commit then if this works?

**Comment by reckart** [comment]
I'd wait on deciding that until an alternative approach has been found to be working :)

**Comment by wpmp** [comment]
@reckart this commit seems to do the trick for me.

**Pull request merged**
