### PR TITLE
Bugfix/857 documents outdated

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
* Necessary overrides to the documentation

**How to test manually**
* Build documentation and search for "webanno"

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation (well - kind of ;) )

### CODE REVIEW

**Comment by reckart** [comment]
@az79nefy 

> Documentation now contains "webanno" mentions.

The only mentions should be in the documentation section on the WebAnno TSV3 format. Where else did you find some? Please make sure that you also use the latest WebAnno 3.5.0-SNAPSHOT artifacts.

**Comment by az79nefy** [comment]
I see "webanno" mentions in the following user-guide sections:

- "Getting started"
- "Getting started > Where to go from here"
- "Core functionalities > Projects > Export"
- "Constraints > Conditional features"
- "Appendices > WebAnno TSV 3.2 File format"

**Comment by reckart** [comment]
The "Getting Started" section is actually overwritten by a file in this PR (`getting-started.adoc`). Maybe you test wrong.

Try this on the command line:

```
$ mvn -U clean install
```

Finally, check in the `inception-app-webapp/target/generated-docs` folder for the generated documentation.

The documentation you access via the "Help" button may not be automatically updated when you build. Also if you use the "Help" button, your browser may cache the data - you'd have to force-reload to see the latest version.

**Comment by az79nefy** [comment]
I now only see "webanno" mentions in:

- Constraints > Conditional features
- Appendices > WebAnno TSV 3.2 File format

**Pull request merged**
