### PR TITLE
#877 - Recommendations not generated when opening a document

### PR DESCRIPTION
**Pull request by Rentier**
**What's in the PR**
* Start TrainingTask instead of PredictionTask

**How to test manually**
1. Configure a project with a recommender (string matching is sufficient, do not enable "always active")
2. Create a few annotations such that the recommender generates suggestions
3. Restart application
4. Open the document again
5. See that there are annotations

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by Rentier** [comment]
I do not exactly know why that fixes it. I assume that the prediction that is triggered by the selection task is too fast so that no training is done before, therefore not marking the contexts ready.

**Comment by reckart** [comment]
The training/prediction happen internally in the selection task. Would it help if the selection task used a private internal context instead of accessing the "normal" one?

**Comment by Rentier** [comment]
The selectiontask should not need a context, as we never save the model for evaluation.

**Comment by reckart** [comment]
Why is the prediction triggered by the selection task?

**Comment by Rentier** [comment]
I do not know. Although I think that it is reasonable that the selection starts the training, so that we know that enabling/disabling is fresh when retraining.

**Comment by reckart** [comment]
The training should be triggered when
* the user opens the document (initialization)
* the user adds/updates/deletes an annotation (data changes)

The prediction should be triggered when
* the training is complete

The evaluation should be triggered when
* every n-th time (including the first time) the training is triggered a selection needs to be performed first

**Pull request merged**
