### PR TITLE
Feature/1353 jump to slot filler

### PR DESCRIPTION
**Pull request by Jackwulujie**
We group 4 are responsible for implementing the function of jumping to slot filler.
Honestly, we don't really understand this issue, especially what slot represents in this application.
First, according to the instructions in the user guide, we have enabled the document metadata function, as follows
67132292-f8efc980-f23a-11e9-9219-05cc0523077c
Then because we don't know what slot represents here, we have no idea how to use the things I created, like test, Jack, yes.
67132386-6dc30380-f23b-11e9-88ea-3b63718d4eaf
Maybe we need to follow this step, but I failed to fill the slot by double-clicking on a span annotation.
Actually, we don't know what will happen when this function is implemented.
Our guess is，we don't know if it is correct.，there can be several annotations on a word, but one of them can be linked to other annotations, which is a slot filler, but we can't see it directly. So in order to distinguish this annotation (slot filler) with link function from other annotations, we should add a visible icon on it.
Do I understand this correctly or can you help me explain it in more detail?

### CODE REVIEW

**Comment by reckart** [comment]
I have updated the [issue description](https://github.com/inception-project/inception/issues/1353) explaining how to create an annotation with slots and how to fill a list.

**Comment by Jackwulujie** [comment]
We are responsible for #1353 Jump to slot filler
We added a new button to the documentnavigator.html page to implement the new functionality and add it to the corresponding configuration file and java file. However, we encountered difficulties when actually coding the function in the documentnavigator.java file. actionShowSelectedDocument needs to use the SourceDocument parameter, but this parameter exists in the docListProvider, we tried a lot of methods but can't extract it.
At present, we can only complete the modification of the front end but the implementation of the function has not been completed yet.

**Comment by Jackwulujie** [comment]
We are responsible for #1353 Jump to slot filler
We added a new button to the documentnavigator.html page to implement the new functionality and add it to the corresponding configuration file and java file. However, we encountered difficulties when actually coding the function in the documentnavigator.java file. actionShowSelectedDocument needs to use the SourceDocument parameter, but this parameter exists in the docListProvider, we tried a lot of methods but can't extract it.
At present, we can only complete the modification of the front end but the implementation of the function has not been completed yet.

**Comment by reckart** [comment]
The UI element to jump to a slot filler has to be with the slot. In the screenshot I added to the issue description, you can see a slot on the right with the role `link` and the filler `School` - so a button to jump to `School` could be e.g. right of the label box. The class is `LinkFeatureEditor`.
The current document can be accessed in that class via `stateModel.getObject().getDocument()`.

**Comment by reckart** [comment]
> Maybe we need to follow this step, but I failed to fill the slot by double-clicking on a span annotation.

Slots can be filled in INCEpTION using a single click - in WebAnno one would need to use a double-click. Thanks for pointing this out, we need to fix the documentation!

**Comment by munterkalmsteiner** [comment]
@Jackwulujie I'm closing this pull request because it is based on an old refactoring branch of yours instead of upstream master. This makes it impossible to review. You can reopen when you think it is ready for review.

**Comment by Jackwulujie** [comment]
> @Jackwulujie I'm closing this pull request because it is based on an old refactoring branch of yours instead of upstream master. This makes it impossible to review. You can reopen it when you have fixed this and when you think it is ready for review.

Sorry, I don't really know what you mean.

**Comment by munterkalmsteiner** [comment]
@Jackwulujie this pull request contains the following commits that do not belong to the feature you try to implement: 19f372e, e9ad4c0, ce935dcde07b84363ccd9d52e2e488adc7538a7e, 42698d883c18d71bf0a8ab99b01f3cace0435b17, d60ed5e3a2b717bc3641c06f5ef7002b707632ad. You can see those [here](https://github.com/inception-project/inception/pull/1476/commits). 
You should base your pull request on a clean branch, not on an old branch that contains unrelated code changes.

**Comment by Jackwulujie** [comment]
> The UI element to jump to a slot filler has to be with the slot. In the screenshot I added to the issue description, you can see a slot on the right with the role `link` and the filler `School` - so a button to jump to `School` could be e.g. right of the label box. The class is `LinkFeatureEditor`.
> The current document can be accessed in that class via `stateModel.getObject().getDocument()`.

Sir, could you please tell us the specific location of the button we need to add? It should be on the top of the page or somewhere in the following figure?
image

**Comment by reckart** [comment]
How about as shown below? I used the [Fontawesome crosshairs icon](https://fontawesome.com/icons?d=gallery&q=crosshairs) here.

68126178-2a140d80-ff4e-11e9-90d8-77061a4a7d2c

**Pull request closed without merging**
