### PR TITLE
#1312 - Embed Docker Compose script into documentation

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Embed script into admin guide and replace `latest` in script with the proper version

**How to test manually**
* Build and check that the Docker Compose script properly appears in the documentation

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by jcklie** [comment]
It looks ok and builds locally, though I would consider making the user and password also environment variables, as there are many places where you need to changes these.

**Comment by reckart** [comment]
I'm not familiar with Docker Compose. Do you want to adapt the PR accordingly?

**Comment by jcklie** [comment]
Done and started locally. I can log in to the db from the command line with the users once I set the credentials via export.

**Comment by reckart** [comment]
@jcklie do you really think this is convenient? Is it a common practice? I'm slightly afraid that people might forget the credentials and then ask us how to recover...

**Comment by jcklie** [comment]
You still have the option of replacing it in the compose file. I am used to do pass credentials in the environment for cloud deployments, like Travis or Heroku. You can also use a file you do not check in which sets these and source it.

**Comment by jcklie** [comment]
See e.g https://docs.docker.com/compose/environment-variables/#the-env-file

**Comment by reckart** [comment]
Roger. Thanks for the initiative and approval :)

**Pull request merged**
