### PR TITLE
#1310 - Linking of spans not working in PDF editor

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- add handling of armed slots in PDF editor to fix linking of spans

**How to test manually**
* Have two layers, one with a link feature to the other
* In the PDF editor create a span and try to link another one to it

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
@wpmp could we include this in the 0.10.x branch instead?

**Comment by wpmp** [comment]
@reckart sure :)

**Comment by wpmp** [comment]
So what is the best way to accomplish this?
Rebase the commit onto the 0.10.x branch, force push and change target branch to 0.10.x?

**Comment by reckart** [comment]
> Rebase the commit onto the 0.10.x branch, force push and change target branch to 0.10.x?

You can try that. An alternative would be to create a new branch/PR based on 0.10.x and then cherry-pick the commit into that one.

**Comment by wpmp** [comment]
Done

**Comment by reckart** [comment]
Sorry for taking so long - this should have been merged ages ago already...

**Comment by wpmp** [comment]
No problem :)

**Pull request merged**
