### PR TITLE
#950 - Add LAPPS Grid external recommender support

### PR DESCRIPTION
**Pull request by jcklie**
**What's in the PR**
* Add new module for LAPPS grid recommender integration

**How to test manually**
* Create a new recommender for NER or POS layer
* Make sure you get recommendations
* Make sure that you can create LAPPS grid recommender just for NER and POS

**Automatic testing**
* [x] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

**Todos**
* [ ] Write documentation
* [ ] Curate list of recommenders that work
* [ ] Write integration test

### CODE REVIEW

**Comment by jcklie** [comment]
For me, almost all of the recommender do not work.

**Comment by reckart** [comment]
@jcklie can you please get in touch with @ksuderman to see what can be done about this?

**Comment by reckart** [comment]
So which ones work and which ones don't?

**Comment by jcklie** [comment]
I debugged some Vassar services and created the following table.

| Name                                                                           | Error Type                                                                                                                                                                                                                       | Link to response              |
|--------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------|
| http://vassar.lappsgrid.org/invoker/anc:lingpipe.tagger_1.1.1-SNAPSHOT         | No tokens, no sentences, no pos tags in response                                                                                                                                                                                 | https://pastebin.com/2VDdg6ti |
| http://vassar.lappsgrid.org/invoker/anc:stanford.tagger_2.1.0-SNAPSHOT         | NullpointerException when calling ServiceClient                                                                                                                                                                                  |                               |
| http://vassar.lappsgrid.org/invoker/anc:weblicht.stanford.parser_1.0.0         | Invalid discriminator type: http://vocab.lappsgrid.org/ns/media/jsonld#lif                                                                                                                                                       |                               |
| http://vassar.lappsgrid.org/invoker/anc:weblicht.stanford.tagger_1.0.0         | Invalid discriminator type: http://vocab.lappsgrid.org/ns/media/jsonld#lif                                                                                                                                                       |                               |
| http://vassar.lappsgrid.org/invoker/anc:gate.tagger_2.3.0                      | Unknown document type : http://vocab.lappsgrid.org/ns/media/jsonld#lif                                                                                                                                                           |                               |
| http://vassar.lappsgrid.org/invoker/anc:lingpipe.tagger_1.1.0                  | Uses two views in the response, the POS are in the second view which Lif2DKPro does not use                                                                                                                                      | https://pastebin.com/7stRryxb |
|                                                                                |                                                                                                                                                                                                                                  |                               |
| http://vassar.lappsgrid.org/invoker/anc:lingpipe.ner_1.1.1-SNAPSHOT            | Uses two views in the response, the NER are in the second view which Lif2DKPro does not use                                                                                                                                      | https://pastebin.com/DCLXJ95C |
| http://vassar.lappsgrid.org/invoker/anc:stanford.ner2_2.1.0-SNAPSHOT           | INVALID INPUT: Unable to find Tokens with POS tags.                                                                                                                                                                              |                               |
| http://vassar.lappsgrid.org/invoker/anc:lingpipe.dictionary_ner_1.1.1-SNAPSHOT | Cannot construct instance of `org.lappsgrid.serialization.lif.Container` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('java.lang.NullPointerException |                               |
| http://vassar.lappsgrid.org/invoker/anc:stanford.ner_2.1.0-SNAPSHOT            | No NER in response                                                                                                                                                                                                               | https://pastebin.com/bgS497r4 |
| http://vassar.lappsgrid.org/invoker/anc:weblicht.stanford.ner_1.0.0            | Invalid discriminator type: http://vocab.lappsgrid.org/ns/media/jsonld#lif                                                                                                                                                       |                               |
| http://vassar.lappsgrid.org/invoker/anc:lingpipe.dictionary_ner_1.1.0          | Cannot construct instance of `org.lappsgrid.serialization.lif.Container` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('java.lang.NullPointerException |                               |
| http://vassar.lappsgrid.org/invoker/anc:lingpipe.ner_1.1.0                     | No NER in response                                                                                                                                                                                                               | https://pastebin.com/aYzLT8QS |

For some, we could fix it by using the right input format (not LIF), some need to be fixed in the service itself I think. Right now, I did not find any service that works for us.

**Comment by reckart** [comment]
@jcklie @ksuderman ok, we get predictions from the ABNER service now :)

**Comment by reckart** [comment]
@jcklie @ksuderman here is a short summary of my changes

* look for the predicted annotations in the last view returned by the LAPPS service, not in the first view
* manually restore tokens to the prediction CAS in case there were not found in the last view returned by the LAPPS service (`extractSuggestions` requires tokens)
* set the "predicted annotation" flag on all annotations of the predicted type in the prediction CAS so they get picked up by `extractSuggestions`

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
