### PR TITLE
Sorted list was not used, hence recommendations appeared in random order

### PR DESCRIPTION
**Pull request by munterkalmsteiner**
**What's in the PR**
Fix an oversight that led to sorted recommendations being ignored, rendering them in random order.

**How to test manually**
Use a recommender with a score feature that produces more than 1 suggested annotation. 
Expected: first suggestion (bottom of list, closest to the text) is the one with the highest score
Actual: the suggestions are not sorted by score  

**Automatic testing**
No GUI testing adopted in project, hence no tests provided

**Documentation**
N/A

### CODE REVIEW

**Comment by reckart** [comment]
@munterkalmsteiner thanks for the PR (and the other one!) - A quick comment on this one: the order in which annotations are rendered is only indicative to the frontend (e.g. brat) which may choose to re-order them (e.g. for layout reasons).

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
I think it would be a good idea to re-base this to the `0.10.x` branch so it can be included in a bugfix release.

**Comment by munterkalmsteiner** [comment]
@reckart Hm, was not able to rebase. Will create new PR based on 0.10.x

**Pull request closed without merging**
