### PR TITLE
#30 - Pre-disambiguate concepts in dropdown list

### PR DESCRIPTION
**Pull request by reckart**
- Introduced new concept linking module
- Added flag to KB to indicate whether it supports entity linking
- Call out to concept linking code in ConceptFeatureEditor if the KB supports it

- [ ] ability to change "support entity linking" flag after a KB has been created.

### CODE REVIEW

**Comment by reckart** [comment]
@rcffc I fixed the build, but I didn't yet get around to testing in the running application. How does the code behave if the resources it tried to load from the classpath are not present?

**Comment by rcffc** [comment]
@reckart It will just ignore those parts of the code.

**Comment by reckart** [comment]
It is not possible to change the "supportConceptLinking" flag after the KB has been saved.

**Comment by reckart** [comment]
I opened a separate issue for editing the concept linking flag: https://github.com/inception-project/inception/issues/40

**Pull request merged**
