### PR TITLE
#2243 - Directly select tags for small tagsets

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Add radio-group-based editor
- Add option to select the preferred editor in the feature traits

**How to test manually**
* Use with tagset <= 5 tags
* Manually configure which editor to use in the feature settings
* Also try with tagsets that have or have not descriptions

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by jcklie** [comment]
I would expect that clicking the radio button updates the brat, but it does not? 

image

I also used Ortography as a layer with 4 tags, but it was an autocomplete by default whereas this issue says <= 5 gets radio.

**Comment by jcklie** [comment]
It would also be nice if clicking on the selected tag would remove/reset the label to none.

**Comment by reckart** [comment]
You need to make sure the tagset does not have "anntotator can add new tags" enabled.

Yes, clicking should indeed update.

**Comment by reckart** [comment]
> It would also be nice if clicking on the selected tag would remove/reset the label to none.

Remember, this is a radio-group, not a multiple-choice component. The selection behavior is determined by the radio group as implemented in the browser. Clicking means selecting, not unselecting. There is the "x" in the feature header to unselect.

**Comment by jcklie** [comment]
> > It would also be nice if clicking on the selected tag would remove/reset the label to none.
> 
> Remember, this is a radio-group, not a multiple-choice component. The selection behavior is determined by the radio group as implemented in the browser. Clicking means selecting, not unselecting. There is the "x" in the feature header to unselect.

I know, but it does not look like radio buttons right now so I wish more functionality

**Review by jcklie — APPROVED** [review]
Works for me

**Comment by jcklie** [comment]
You should not be able to select radio buttons if "add new tags" is true for the tagset/feature

**Comment by jcklie** [comment]
Maybe make tagsets default closed

**Comment by reckart** [comment]
For the inclined reader: the "operation" feature we used here to test is by default not shown in the label of orthography annotations. For other layers+features (e.g. Named entity / value) it works.

**Pull request merged**
