### PR TITLE
#1633 Exception when session expires

### PR DESCRIPTION
**Pull request by UWinch**
**What's in the PR**
* Fixes NPE when storing curation settings for a user.

**How to test manually**
* see Issue

### CODE REVIEW

**Comment by UWinch** [comment]
I wanted to save on database accesses. I thought flush is necessary to actually write through to the database. Do you think I should change something before you accept the PR?

**Comment by reckart** [comment]
Saving on DB accesses is ok if they happen often (I'm just as we speak in the process of resolving some performance issues due to DB hammering). But in this case, how often does the user change  the curation settings? Almost never probably. 

So it wouldn't hurt saving the settings immediately. You can still keep them in memory (in the annotator state) to avoid having to read them from the DB on every action. 

I was wondering if you wanted to save only on session end in case a user logs in using two different sessions simultaneously (e.g. two browsers) - but that's something generally discouraged with INCEpTION / WebAnno anyway because it can break all kinds of things.

The `@Transactional` annotation takes care of saving stuff to the DB, so the explicit flush is not needed in most cases.

I'm a bit undecided on merging it without change. Well, if it works, should be ok, right? But I wanted to make you aware of some design issues in the code. You can have another look at it or we merge it as running code (note, I didn't check (yet) if it actually works) and book any remaining comments under technical dept to be addressed later.

**Comment by UWinch** [comment]
I understand your points. To be honest, I would like to merge it now and come back to the issues when I work on the next features for this (e.g. aggregating user annotations) because I would like to work on something different for a time. I would make a note on this in the associated issue check list.

**Comment by reckart** [comment]
Ok, we don't need to do a big refactoring now. It would be good if we could remove the `.flush()` call though because I think it is not needed at all. 

The fix you added was checking if the user existed in the DB and if not bailing out. So I guess what might have happened here was that for testing purposes, I deleted a user directly from the DB and then the session of this user timed out. Probably this would never happen under normal circumstances because the application does not (yet) allow to delete users.

Anyway, maybe you could add a comment to the check you added, e.g. something like `If the user no longer exists, we do not store the curation settings either`.

**Comment by UWinch** [comment]
@reckart ok to merge now?

**Pull request merged**
