### PR TITLE
#1222 - New page for simulating evaluation

### PR DESCRIPTION
**Pull request by Sibgha360**
**What's in the PR**
* Evaluation Simulation Page in the project menu

**How to test manually**
* Open Project
* Click on the Evaluation Simulation Menu Option
* Select a recommender. Press Start
* The learning Curve should show up

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by UWinch** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@Sibgha360 @UWinch what remains to be done here?

**Comment by UWinch** [comment]
We still need to do some tweaking of the html to fit the evaluation curve better to the page. Sibgha should be able to get back to it soon.

**Comment by Sibgha360** [comment]
> * I can no longer configure recommenders for a project:
>   Go to settings -> recommenders -> create
> * On this same page the bottom of the Recommenders list which contains the Create button is not fixed to the list (compare with knowledge bases list on the knowledge bases tab)
> * There is also a checkstyle-error for the INCEpTION class becuase of an unused import

Fixed.

**Pull request merged**
