### PR TITLE
#1090 - Crash when changing PDF document

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- catch if pdfExtractFile and documentModel are null when creating span annotations in the PDF editor

**How to test manually**
1. Open a PDF document in PDF editor
2. Open the `Open` dialog to change the document
3. Select a document in the dialog
4. You need to be quick so make the selection by pressing enter and immediately select some text in the old document
5. There no should be an error warning instead of a NPE which lead to a complete crash

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
What's wrong with jenkins? :/

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
What is Jenkins doing that annoys you?

**Comment by wpmp** [comment]
I experience a lot of builds failing like in #1330 or #1410
This also happened here before I triggered a new build

**Comment by reckart** [comment]
And did you check the build logs to figure out the cause of the failure?

**Comment by wpmp** [comment]
Yes
```
21:41:53 ERROR: Error fetching remote repo 'origin'
21:41:53 hudson.plugins.git.GitException: Failed to fetch from https://github.com/inception-project/inception
```
I guess this is what lets the build fail, but I don't know / understand why this is the case.

**Comment by reckart** [comment]
Seems like the Windows-based build node has some issue. I'm trying to re-start it. Maybe that fixes the problem.

**Pull request merged**
