### PR TITLE
#1715 AL sidebar is missing

### PR DESCRIPTION
**Pull request by UWinch**
Active Learning sidebar was no longer shown.

**What's in the PR**
* Fixed AL autoconfiguration to be conditional on recommendersidebar factory instead of the sidebar itself.
* Made RecommendationMetrics conditional on recommenders enabled.

**How to test manually**
* Open the annotation page and check that the AL sidebar is there
* Check e.g. with jconsole that metric on enabled recommenders is calculated
* Test with settings `recommender.enabled=false`-> neither recommendersidebar nor AL sidebar should be shown
* Test with settings `recommender.active-learning.enabled=false`-> recommendersidebar should be shown but not AL sidebar

### CODE REVIEW

**Comment by reckart** [comment]
Why is the recommender sidebar a prerequisite for the AL sidebar? Does it not rather depend on the AL service and the sidebar itself?

**Comment by UWinch** [comment]
> Why is the recommender sidebar a prerequisite for the AL sidebar? Does it not rather depend on the AL service and the sidebar itself?

You implemented it here https://github.com/inception-project/inception/pull/1401/files#diff-b8ffb6f8f914b63f944d6a55e59c2719. I assume it's for the case that recommenders are disabled via config switch. In this case AL would also not be possible.

**Comment by UWinch** [comment]
Can be reviewed/merged.

**Comment by reckart** [comment]
@UWinch from my side you can merge it once Jenkins approves.

**Pull request merged**
