### PR TITLE
Bugfix for #2467 and partially addresses #2442

### PR DESCRIPTION
**Pull request by antonyscerri**
**What's in the PR**
This is a fix for bug #2467 and it also partially address #2442 (I realised it also only looked at the first annotation and so would create a duplicate even if one of the others was a match).

**How to test manually**
Assuming you use the named entity layer. Using a search for words you should be able to create multiple sets using a different value feature tag, with repeated calls with the same tag not creating duplicates. You will also then be able to delete any matching annotation using any of the tag values you have created (assuming you have more than one stacked up).

Note the exact behaviour on creating multiple annotations when one exists with matching values alongside the override isn't really defined well so I went with just trying to avoid creating duplicates when not overriding. However if override is on then it will set all matches to the template annotations as before, this may result in duplicates if there were multiple distinct ones beforehand.

**Automatic testing**
No matching test class

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
I tried to reproduce  #2442 on this branch, but it doesn't seem to happen here. Why do you say that  #2442 is only partially addressed?

I also noted that if the span with the link feature has already filled slots, then the copies also end up with the same slot fillers - and I wonder if this is a good idea or not...

**Comment by antonyscerri** [comment]
Its partially addressed #2442 because i added the loop to check if an existing annotation at the given span matched and then it won't create one. This did not explicitly address the issue of using a link feature and the related matching check with FSArray (which with a default slot selected will always be an intance, not null, with zero length unless the user has actually picked an annotation to link to). So I basically added the same looping check as in the delete for completeness, with the caveat around the exact behaviour around overriding and if a link feature is used whether that should even be copied (whether it should be removed, or just not allowed).

**Comment by antonyscerri** [comment]
I should have also mentioned that same change to the create behaviour will prevent duplicates in other cases now.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
