### PR TITLE
#221 - Unable to import medium-sized local KBs

### PR DESCRIPTION
**Pull request by reckart**
- disable the inferencer
- fix test files which wrongly use the rdfs prefix instead of the rdf prefix in some cases

### CODE REVIEW

**Comment by Rentier** [comment]
```
[WARNING] Unused declared dependencies found:
[WARNING]    org.eclipse.rdf4j:rdf4j-sail-inferencer:jar:2.2.4:compile
```

**Comment by Rentier** [comment]
@reckart  It would be nice if you could remove the `aIncludeInferred` flag from methods in e.g. KBService, because it would do nothing now from what I think.

**Comment by reckart** [comment]
@rentier it would still do something for remote KBs.

**Comment by Rentier** [comment]
@reckart  You still have that dependecy issue

**Comment by reckart** [comment]
@Rentier I'm presently busy elsewhere; coming back to this later; feel free to fix it.

**Pull request merged**
