### PR TITLE
#936 - maven-enforcer-plugin enforces wrong Java version

### PR DESCRIPTION
**Pull request by jcklie**
**What's in the PR**
* Setting the version maven enforces to `1.8`

**How to test manually**
* Build INCEpTION on the command line

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@jcklie Any reason why this doesn't go into the `0.7.x` branch?

**Comment by jcklie** [comment]
No particular reason. I always forget to branch from the release branch.

**Comment by reckart** [comment]
I'd suggest to cherry-pick this also over to 0.7.x

**Pull request merged**
