### PR TITLE
Feature/735 fix building on java 11

### PR DESCRIPTION
**Pull request by reckart**

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
This PR sets the minimal Java version required for INCEpTION to 9 - meaning it won't build or run on older versions. Note that right now the JDK on our test server does not meet this requirement and needs to be updated before this can finally be merged. Please see if the branch runs on your systems or if you might also have to upgrade Java.

**Comment by az79nefy** [comment]
Upgraded my Java version to 11, works for me now as well.

**Comment by reckart** [comment]
@Sibgha360 @MdeBoer95 @wpmp please upgrade your local environment, test the branch builds and approve the PR.

**Comment by reckart** [comment]
@MdeBoer95 @Sibgha360 What about you?

**Comment by reckart** [comment]
@MdeBoer95 awaiting final approval from you.

**Pull request merged**
