### PR TITLE
#287 - Search mode - limit to within document

### LINKED ISSUE #287: Search mode - limit to within document
The current search mode searches across all documents in a project. It could be useful to limit this function (e.g. with a checkbox) to 'only current document'. This allows for example to jump between all cases of an annotation to check consistency (e.g. I want to make sure I annotated all mentions of 'book' in the current document as 'abstract', not 'object').

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Add toggelable options pane to the search sidebar
- Added option to limit search to the current document
- Added documentation
- Added unit test checking if the limiting to a given document works
- Added ability to ask search service if indexing is in progress on a given project
- Added information about limiting query to a given document to the search event and event logging
- Fixed unrelated bug in the MTasDocumentIndex which caused the unit tests to fail when executed in a specific order
- Cleaned up MtasDocumentIndexTest
- Adjusted log levels for unit test
- Removed spurious key bindings in annotation sidebar and corresponding dependency in the POM
- Closes #287 

**How to test manually**
* Open annotation page and open annotation sidebar
* Click on the cogs symbol and re-index the project
* Search for some word which occurs in more than one document
* Tick the "Limit to current document" checkbox and search again

**Automatic testing**
* [x] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by MdeBoer95** [comment]
@reckart I get 
```Error:(319, 57) java: incompatible types: java.lang.String cannot be converted to de.tudarmstadt.ukp.clarin.webanno.security.model.User``` 
in **MtasDocumentIndex.java** when I try to start the application on this branch.
Any Idea?

**Comment by reckart** [comment]
@MdeBoer95 yes... I need to commit some changes to WebAnno... will commit and get back to you.

**Comment by reckart** [comment]
@MdeBoer95 done: https://github.com/webanno/webanno/commit/799e6d911c9229cc839f441e435509cd7ba9a532

If you already have a local clone of WebAnno, you can just pull the latest changes from master and run a local build. Then this PR should also be fine.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@MdeBoer95 ok, Jenkins is happy again which means the necessary changes in WebAnno are now also available via Maven.

**Pull request merged**
