### PR TITLE
#1634 - Explicit UI for accepting/rejecting recommendations

### PR DESCRIPTION
**Pull request by waleedabdeen**
**What's in the PR**
* Set actionButtons flag on VSpan in RecommendationSpanRenderer to show accept/reject button next to each recommender's span.

**How to test manually**
* by putting the mouse over annotation span

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
@waleedabdeen would you say from your perspective, this is done?

**Comment by waleedabdeen** [comment]
@reckart I will do a quick check after the merge from the master branch and see if anything is left.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
I fixed up a few smaller things after consolidating the changes into this PR. Looks like it works in general.

It seems that the info tooltip/popup no longer shows up on suggestions - instead the buttons are shown. 

The accept/reject buttons may be a wee bit tiny. 

 Not sure if this is how it is intended to look.

Screenshot 2021-02-06 at 10 50 28

When I hover over the suggestion, the reject button appears directly under the mouse cursor above the annotation label. It seems something is a bit off here.

**Comment by reckart** [comment]
If I set the font zoom to 150% in the annotation preferences dialog, it looks even more off.

Screenshot 2021-02-06 at 10 52 49

**Comment by waleedabdeen** [comment]
> I fixed up a few smaller things after consolidating the changes into this PR. Looks like it works in general.
> 
> It seems that the info tooltip/popup no longer shows up on suggestions - instead the buttons are shown.
> 
> The accept/reject buttons may be a wee bit tiny.
> 
> Not sure if this is how it is intended to look.
> 
> Screenshot 2021-02-06 at 10 50 28
> 
> When I hover over the suggestion, the reject button appears directly under the mouse cursor above the annotation label. It seems something is a bit off here.

It is not intended to show in this way. The accept/reject button should show on the left/right side of the annotation. Something must got missed up during the update.

**Comment by waleedabdeen** [comment]
> If I set the font zoom to 150% in the annotation preferences dialog, it looks even more off.
> 
> Screenshot 2021-02-06 at 10 52 49

I have not tested in Zoom before. I will check that out.

**Comment by waleedabdeen** [comment]
The one issue that i am currently facing is getting the action to work. Wicked seems to through an error when we send a request with the new accept action.

**Comment by reckart** [comment]
I think my last push should have fixed that error.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@jcklie @UWinch Could you please try this branch out and let us know what you think about the usability? It works on spans, but not on relations. Possibly need to force-reload / reload-without-cache to get the JS changes into the browser.

**Comment by jcklie** [comment]
I like it, and it is better than the old way. Two things: I would make the font a bit more legible and move the labels a bit up in the box, also the accept/reject should disappear when clicking while still hovering over the recommendation bubble.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
