### PR TITLE
#639 - Refactoring KB Module - Change UI structure

### PR DESCRIPTION
**Pull request by MdeBoer95**

### CODE REVIEW

**Comment by reckart** [comment]
Changing this to 0.7.x (master) because the PR is against master already and master has already been merged into this PR branch.

**Comment by reckart** [comment]
@MdeBoer95 where are we with this one?

**Comment by MdeBoer95** [comment]
@reckart I have a strange bug and I don't know why it happens. When I create a knowledge base and then switch to the KBPage the kb appears empty. When I then go to the kb settings again, click on save and then go back to the KBPage it works. 
The rest is done.

**Comment by reckart** [comment]
@MdeBoer95 is it done from your perspective? Should this now be reviewed/tested?

**Comment by reckart** [comment]
@MdeBoer95 Changing the full text mode setting doesn't work for me. If I change it, leave the page and come back it always resets to "No full text search support".

**Comment by MdeBoer95** [comment]
@reckart fixed it.

**Pull request merged**
