### PR TITLE
Feature/2189 experimental annotation api and editor

### PR DESCRIPTION
**Pull request by christophscheunemann**
**What's in the PR**
* Basic modules for new annotation API (inception-api-annotation-experimental) and custom editor (inception-experimental-editor)
* Package structure and basic files
* Basic features and integration of the API in this PR

### CODE REVIEW

**Comment by reckart** [comment]
@christophscheunemann the PR deletes files from the PDF module - is that intentional?

**Comment by christophscheunemann** [comment]
@reckart No, this is not intentional and will be reverted

**Comment by reckart** [comment]
@christophscheunemann the PR also modifies several files from the PDF module. Also, some files contain the license header twice.

**Comment by christophscheunemann** [comment]
@reckart Please review the module inception-api-annotation-experimental
-> Before merging I want to fix the MDC issue (repository path is null) and the timer issue in the LogoutPanel.html

**Review by reckart — CHANGES_REQUESTED** [review]
There are many (formatting) changes irrelevant to the PR, e.g. formatting changes in the MenuBar HTML code, in unrelated POMs and source files, etc. etc. - can you please revert them?

Jenkins reports the build as broken, could you please look into fixing that.

**Comment by christophscheunemann** [comment]
@reckart Yes of course, I will revert the formatting changes. About the build error, this comes from the inception-sharing module, which i do not have anything to do with. However, I will check this.

**Comment by reckart** [comment]
@christophscheunemann ok, then let me check the issue - I had merge conflicts on the sharing module when I updated the branch and probably the failure comes from them.

**Comment by christophscheunemann** [comment]
Alright, thank you

**Comment by reckart** [comment]
@christophscheunemann I reverted all changes in the sharing module. Going forward, it would be great if you could review your changes before you commit and revert spurious changes before you commit so we don't have to do cleaning up after.

**Comment by christophscheunemann** [comment]
@reckart Ok thank you. Yes of course I will, sorry for that.

**Comment by reckart** [comment]
* I have imported the new modules in Eclipse and started the application.
* Then I created a project and imported a text. 
* However, the new editor type did not show in the editor selection dropdown on the annotation page.
* I checked the auto-config file in the new module, but there appears to be no feature toggle.

**Comment by reckart** [comment]
@christophscheunemann Please make two additional changes:

1) ensure that the webapp module actually depends on the new experimental modules so their functionality can become available in the application
2) add a feature switch property which can be used do en/disable all the new beans in this PR - off by default (i.e. by default none of the beans should be instantiated during startup)

When I turn on the toggle, I would expect the typescript editor dummy to become available in the editor dropdown in the preferences on the annotation page (and that it has its basic dummy functionality working).

**Comment by christophscheunemann** [comment]
@reckart Added spring configuration as requested. The experimental Editor and API can now be enabled with: ui-experimental.enabled = true
-> When enabled, the editor becomes selectable in the annotation editor preferences. Furthermore, when using the "Experimental Editor" a websocket connection will be automatically established (proofs correctly loaded API)
 ->The connection can be seen as a system.out on the server and in the console log on the client side)

**Comment by reckart** [comment]
I have added the feature switch property to my settings.properties file, but the "typescript editor" still doesn't show up on the annotation page. It appears as if the webapp module is still not depending on the new experimental modules, so they are not loaded. @christophscheunemann I am surprised you get it running without this dependency.

**Comment by christophscheunemann** [comment]
@reckart Yes sorry, seems the change in the webapp was unstaged in the commit. Pushed the updated version. Should be working now.

**Comment by reckart** [comment]
When I start the application now, I get this error:

```
2021-05-23 12:58:03 [main] ERROR [SYSTEM] SpringApplication - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [de.tudarmstadt.ukp.inception.INCEpTION]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'websocketConfig' for bean class [de.tudarmstadt.ukp.inception.experimental.api.websocket.WebsocketConfig] conflicts with existing, non-compatible bean definition of same name and class [de.tudarmstadt.ukp.inception.websocket.config.WebsocketConfig]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) ~[spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144) [spring-boot-2.4.5.jar:2.4.5]
	at de.tudarmstadt.ukp.inception.INCEpTION.run(INCEpTION.java:217) [classes/:?]
	at de.tudarmstadt.ukp.inception.INCEpTION.main(INCEpTION.java:222) [classes/:?]
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'websocketConfig' for bean class [de.tudarmstadt.ukp.inception.experimental.api.websocket.WebsocketConfig] conflicts with existing, non-compatible bean definition of same name and class [de.tudarmstadt.ukp.inception.websocket.config.WebsocketConfig]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:132) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:296) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207) ~[spring-context-5.3.6.jar:5.3.6]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175) ~[spring-context-5.3.6.jar:5.3.6]
	... 14 more
```

I have these settings in my `settings.properties`:

```
websocket.enabled=true
websocket.loggedevent.enabled=true

ui.experimental.enabled=true
```

**Comment by christophscheunemann** [comment]
@reckart Ahh, good that you have checked that. My bean had the same name as Utes'. I changed my Bean name. Now everything works properly, even though when both are enabled.

**Comment by reckart** [comment]
@UWinch @christophscheunemann It seems to me the two beans are doing the same thing - shouldn't we maybe pull it out or have the experimental API building on the websocket support from our websocket modules?

**Comment by christophscheunemann** [comment]
@reckart Alright, I'll try to remove my controller and reuse Utes'. Should be possible. I'll give you a notice once I've done it.

**Comment by christophscheunemann** [comment]
@reckart Done. Using Utes' websocket configuration now. However, I need to talk to her due to access denied issues now. 

Still, when enabling:

websocket.enabled: true
ui.experimental.enabled: true

the experimental annotation Editor will be used and is selectable in the annotation preferences. Initally, a websocket connection is opened, so the API is called via the other ws endpoint, however on requesting a new document, only a "access denied" is received and the connection is closed.

**Comment by reckart** [comment]
I can now see the experimental editor in the editor dropdown and switch to it. However, when I do this, the editor area remains empty and I get the following error in the browser console:

Screenshot 2021-05-27 at 23 20 21

It appears as if a hard-coded context name instead of a relative URL is used for setting up the websocket connection. The context name can be different from instance to instance - it can even be empty (i.e. INCEpTION can run e.g. directly on `localhost:8080`). The URLs can even be different depending on how the client accesses the server - therefore links/requests should better use a relative URL.

**Comment by christophscheunemann** [comment]
@reckart Relativ URL now used for the WS connection. Thank you for the hint.
Btw in this PR, the Editor will only show that the connection is established in both logs, however the editor itself is empty. The other PR for #2196 contains some data in the Experimental Editor. I will show you the new features and implementaion Details on Tuesday via screen share.

**Comment by reckart** [comment]
@christophscheunemann tested again - but this time I get a new error message:

Screenshot 2021-06-04 at 13 46 01

**Comment by christophscheunemann** [comment]
Hm, thats weird. Everything works here fine with the relativ URL.
What is your exact URL when you go to the annotation page?

**Comment by reckart** [comment]
The error message is generated in `de.tudarmstadt.ukp.clarin.webanno.ui.core.page.ProjectPageBase.getProjectFromParameters()` when I access the annotation page and then reload it.

When I call `RequestCycle.get().getRequest().getOriginalUrl()` e.g. via the debug expression view at that point, it tells me the URL is `p/ws-endpoint`.

Stack trace: 

```
Daemon Thread [http-nio-8080-exec-10] (Suspended)	
	owns: NioEndpoint$NioSocketWrapper  (id=2145)	
	ProjectDashboardPage(ProjectPageBase).getProjectFromParameters() line: 131	
	60030945.get() line: not available	
	LoadableDetachableModel$1.load() line: 216	
	LoadableDetachableModel$1(LoadableDetachableModel<T>).getObject() line: 128	
	ProjectDashboardPage(ProjectPageBase).<init>(PageParameters) line: 61	
	ProjectDashboardPage.<init>(PageParameters) line: 62	
	NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[]) line: not available [native method]	
	NativeConstructorAccessorImpl.newInstance(Object[]) line: 62	
	DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 45	
	Constructor<T>.newInstance(Object...) line: 490	
	DefaultPageFactory.newPage(Constructor<C>, PageParameters) line: 171	
	DefaultPageFactory.newPage(Class<C>, PageParameters) line: 99	
	DefaultMapperContext.newPageInstance(Class<IRequestablePage>, PageParameters) line: 94	
	PageProvider$Provision.getPage() line: 369	
	PageProvider.getPageInstance() line: 170	
	WebPageRenderer(PageRenderer).getPage() line: 78	
	WebPageRenderer.respond(RequestCycle) line: 231	
	RenderPageRequestHandler.respond(IRequestCycle) line: 202	
	RequestCycle$HandlerExecutor.respond(IRequestHandler) line: 910	
	RequestCycle$HandlerExecutor(RequestHandlerExecutor).execute(IRequestHandler) line: 63	
	RequestCycle.execute(IRequestHandler) line: 294	
	RequestCycle.processRequest() line: 255	
	WicketFilter.processRequestCycle(RequestCycle, WebResponse, HttpServletRequest, HttpServletResponse, FilterChain) line: 277	
	WicketFilter.processRequest(ServletRequest, ServletResponse, FilterChain) line: 208	
	WicketFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 307	
	ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 189	
	ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 162	
	OpenEntityManagerInViewFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 186	
	OpenEntityManagerInViewFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 119	
	ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 189	
	ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 162	
	LoggingFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 58	
	ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 189	
	ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 162	
	OpenCasStorageSessionForRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 50	
	ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 189	
	ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 162	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 327	
	FilterSecurityInterceptor.invoke(FilterInvocation) line: 115	
	FilterSecurityInterceptor.doFilter(ServletRequest, ServletResponse, FilterChain) line: 81	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	ExceptionTranslationFilter.doFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 119	
	ExceptionTranslationFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 113	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	SessionManagementFilter.doFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 126	
	SessionManagementFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 81	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	AnonymousAuthenticationFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 105	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	RememberMeAuthenticationFilter.doFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 101	
	RememberMeAuthenticationFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 92	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	SecurityContextHolderAwareRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 149	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	RequestCacheAwareFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 63	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	ConcurrentSessionFilter.doFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 147	
	ConcurrentSessionFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 125	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	LogoutFilter.doFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 103	
	LogoutFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 89	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	HeaderWriterFilter.doHeadersAfter(HttpServletRequest, HttpServletResponse, FilterChain) line: 90	
	HeaderWriterFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 75	
	HeaderWriterFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 119	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	SecurityContextPersistenceFilter.doFilter(HttpServletRequest, HttpServletResponse, FilterChain) line: 110	
	SecurityContextPersistenceFilter.doFilter(ServletRequest, ServletResponse, FilterChain) line: 80	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	WebAsyncManagerIntegrationFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 55	
	WebAsyncManagerIntegrationFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 119	
	FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse) line: 336	
	FilterChainProxy.doFilterInternal(ServletRequest, ServletResponse, FilterChain) line: 211	
	FilterChainProxy.doFilter(ServletRequest, ServletResponse, FilterChain) line: 183	
	DelegatingFilterProxyRegistrationBean$1(DelegatingFilterProxy).invokeDelegate(Filter, ServletRequest, ServletResponse, FilterChain) line: 358	
	DelegatingFilterProxyRegistrationBean$1(DelegatingFilterProxy).doFilter(ServletRequest, ServletResponse, FilterChain) line: 271	
	ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 189	
	ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 162	
	OrderedRequestContextFilter(RequestContextFilter).doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 100	
	OrderedRequestContextFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 119	
	ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 189	
	ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 162	
	OrderedFormContentFilter(FormContentFilter).doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 93	
	OrderedFormContentFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 119	
	ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 189	
	ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 162	
	OrderedCharacterEncodingFilter(CharacterEncodingFilter).doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain) line: 201	
	OrderedCharacterEncodingFilter(OncePerRequestFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 119	
	ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse) line: 189	
	ApplicationFilterChain.doFilter(ServletRequest, ServletResponse) line: 162	
	StandardWrapperValve.invoke(Request, Response) line: 202	
	StandardContextValve.invoke(Request, Response) line: 97	
	NonLoginAuthenticator(AuthenticatorBase).invoke(Request, Response) line: 542	
	StandardHostValve.invoke(Request, Response) line: 143	
	ErrorReportValve.invoke(Request, Response) line: 92	
	StandardEngineValve.invoke(Request, Response) line: 78	
	CoyoteAdapter.service(Request, Response) line: 357	
	Http11Processor.service(SocketWrapperBase<?>) line: 374	
	Http11Processor(AbstractProcessorLight).process(SocketWrapperBase<?>, SocketEvent) line: 65	
	AbstractProtocol$ConnectionHandler<S>.process(SocketWrapperBase<S>, SocketEvent) line: 893	
	NioEndpoint$SocketProcessor.doRun() line: 1707	
	NioEndpoint$SocketProcessor(SocketProcessorBase<S>).run() line: 49	
	ThreadPoolExecutor(ThreadPoolExecutor).runWorker(ThreadPoolExecutor$Worker) line: 1128	
	ThreadPoolExecutor$Worker.run() line: 628	
	TaskThread$WrappingRunnable.run() line: 61	
	TaskThread(Thread).run() line: 834	
``

**Comment by reckart** [comment]
Looking at the browser console when I hit the breakpoint, this is the request being processed:

Screenshot 2021-06-04 at 18 15 06

**Comment by reckart** [comment]
The URL of the annotation page when I access this on my machine is `http://localhost:8080/p/394/annotate?2#!d=43782&f=1`

**Comment by christophscheunemann** [comment]
@reckart Ahh I see the issue, thanks for the screenshot.

**Comment by christophscheunemann** [comment]
The connection point for you should be: http://localhost:8080/ws-endpoint.
As my application has the  additional context"/inception_app_webapp_war_exploded/" I have to connect to  http://localhost:8080/inception_app_webapp_war_exploded/ws-endpoint.
That was really helpful thanks, I'll fix that.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@christophscheunemann Please let me know when I can test again.

**Comment by christophscheunemann** [comment]
@reckart Sorry, made the overhaul for the other PR first (no more sentences but offsets). Hopefully this PR now works for you. 
If not, let me know and I'll try to find another solution.

**Comment by reckart** [comment]
Ok, so if I run as a simple Java app under `http://localhost:8080`, I do not get any errors, but I also do not see anything. Shouldn't I be seeing something? I dimly remember a connect button or something like that and some indicator that connection worked?

But if I run in Tomcat again under `http://localhost:8080/inception-app-webapp/`, then I get this error now in the JS console:

Screenshot 2021-06-06 at 19 22 27

**Comment by reckart** [comment]
@christophscheunemann You should have a look at the  `de.tudarmstadt.ukp.inception.websocket.footer.LoggedEventFooterPanel` and the corresponding Vue component that @UWinch did. There, the WebSocket URL is constructed by the server and send to the client as a parameter - the client does not have to construct the URL itself.

**Comment by reckart** [comment]
You also seem to be having unrelated changes outside your modules again:

Screenshot 2021-06-06 at 19 52 25

**Review by reckart — APPROVED** [review]

**Pull request merged**
