### PR TITLE
#2735 - Document websocket reverse proxy config

### PR DESCRIPTION
**Pull request by jcklie**
**What's in the PR**
- Unify INCEpTION config for reverse proxy setup

**How to test manually**
* No specific test procedure

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by jwijffels** [comment]
What worked for me is running Inception 21.5 behind [Keycloak](https://www.keycloak.org/) using [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc) in the setup of external authentication as described at https://inception-project.github.io/releases/21.5/docs/admin-guide.html#sect_security_preauth

Maybe it makes sense to add such things to the documentation:

My apache virtual host looks pretty much like this:

```
<VirtualHost *:443>
  ServerName myprefix.mydns.be
  ServerAlias www.myprefix.mydns.be  
  ## Pass user access to Keycloak
  OIDCProviderMetadataURL https://iam.mydns.be/auth/realms/realmxyz/.well-known/openid-configuration
  OIDCRedirectURI https://myprefix.mydns.be/p/projectxyz
  OIDCCryptoPassphrase a-random-password
  OIDCClientID inception-client
  OIDCRemoteUserClaim email
  OIDCAuthNHeader remote_user
  OIDCInfoHook userinfo
  <Location />
    AuthType openid-connect
    Require valid-user
    LogLevel debug
  </Location>      
  ProxyRequests Off
  ProxyPreserveHost Off
  ProxyPass / http://computer01x:18080/
  ProxyPassReverse / http://computer01x:18080/
  Include /etc/apache2/options-ssl-apache.conf
  SSLCertificateFile /etc/apache2/fullchain.cer
  SSLCertificateKeyFile /etc/apache2/privkey.pem   
</VirtualHost>
```

I have `/srv/inception/settings.properties` looking pretty much like this

```
database.url=jdbc:mariadb://mymariadb:3306/inception?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
database.username=inception
database.password=$INCEPTION_PWD
# 60 * 60 * 24 * 30 = 30 days
backup.keep.time=2592000
# 60 * 5 = 5 minutes
backup.interval=300
backup.keep.number=10
useSSL=false
allowPublicKeyRetrieval=true
serverTimezone=UTC
server.port=18080
server.use-forward-headers=true
server.tomcat.internal-proxies=127\.0\.[0-1]\.1
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.accesslog.request-attributes-enabled=true
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.protocol-header-https-value=https
server.use-forward-headers=true
wicket.core.csrf.enabled=false
wicket.core.csrf.no-origin-action=allow
remote-api.enabled=true
annotation.default-preferences.page-size=2000
auth.mode                     = preauth
auth.preauth.header.principal = remote_user
auth.preauth.newuser.roles    = ROLE_PROJECT_CREATOR
```

**Comment by reckart** [comment]
We seem to be able to get along without setting all the Tomcat and server headers but instead just using these three while running behind Apache HTTPD/nginx:

```
# Set port
server.port=12345
# Running at //hostname/inception
server.servlet.context-path=/inception
# Running behind a reverse proxy
server.forward-headers-strategy=NATIVE
```

Additionally, we need to set these for CSRF:

```
wicket.core.csrf.accepted-origins[0]=hostname.com
wicket.core.csrf.accepted-origins[1]=https://hostname.com
```

And in Apache HTTPD:

```
<Proxy http://localhost:12345/inception>
  Order Deny,Allow
  Deny from none
  Allow from all
</Proxy>

<!-- The additional proxypass for .../ws is required for INCEpTION >= 22.0 but also doesn't hurt before -->
ProxyPass /inception/ws ws://localhost:12345/inception/ws retry=0
ProxyPass /inception http://localhost:12345/inception retry=0
ProxyPassReverse /inception https://hostname.com/inception
```

**Comment by reckart** [comment]
@jwijffels you use a modified version of INCEpTION, right? What do you need the `allowPublicKeyRetrieval=true` for?

**Comment by jwijffels** [comment]
> @jwijffels you use a modified version of INCEpTION, right? What do you need the `allowPublicKeyRetrieval=true` for?

The config above used your distributed jar file of version 21.5, allowPublicKeyRetrieval was probably a leftofer of my upgrade of version 19.5

> We seem to be able to get along without setting all the Tomcat and server headers but instead just using these three while running behind Apache HTTPD/nginx:

Thanks for the feedback. I'll try to remove some of the settings to see if that still gives a working system.

**Pull request merged**
