### PR TITLE
#958 - kb instance not properly filtered when annotating

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**

- Factor auto-complete field for KB items into a separate re-usable class
- Use this class in the ConceptFeatureEditor and on the KB page
- Fix the search on the KB page mainly by properly handling cases where withLabelMatchingExacltlyAnyOf or withLabelContainingAnyOf are called with an emtpy argument list
- Updated documentation (user + developer)

**How to test manually**
* Go to the KB page and search for some class or instance

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by MdeBoer95** [comment]
Works pretty well. Just a few smaller things.
- I found one strange case:
auswahl_008

- The autocomplete field shows entities, where at least 4 characters match.
So when I want to search for ```wine``` I have to type the whole word.
Is that the intended behaviour?

- I would suggest to show a badge for each item in the search results that indicates the type(Concept, Instance, Property). That makes it easier to find something on the first try if for example a concept and a property have the same name but with different casing. But that should be something for a separate Issue.
auswahl_009

**Comment by reckart** [comment]
> "Region" -> "wine"
That looks indeed strange. I can reproduce it. I also note that when clicking on the result (or any also on the results I get when searching for "wine" in the first place) the respective item doesn't really load in the class/instance detail editor. I'd be inclined to open a separate issue/bug for this. WDYT?

> The autocomplete field shows entities, where at least 4 characters match.
  So when I want to search for `wine` I have to type the whole word.
  Is that the intended behaviour?

Yes. Virtuoso won't allow to do a wildcard search for words with less than four characters. So you can search for `wine` and `wine*` but not for `win*`. To be consistent across backends and because searches for short prefixes tend to yield many results and thus become slow, no wildcard search is attempted if the entered query is four characters or less. However, even for shorter queries, an exact-match query is performed, so if you enter `X` and there is an entry labelled `X`, you should find it.

> I would suggest to show a badge for each item in the search results that indicates the type(Concept, Instance, Property).

That is a good idea. The question is how much it slows down the process if we do this. But this needs to be found out. Could you please open a new issue for your idea?

**Comment by MdeBoer95** [comment]
Yes, I will open corresponding issues for the bug and the visual enhancement.

**Comment by MdeBoer95** [comment]
> Yes, I will open corresponding issues for the bug and the visual enhancement.

Created Issues #979 and #980.

**Comment by reckart** [comment]
Thx

**Pull request merged**
