### PR TITLE
#939 - PDF editor loads wrong PDF

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
* remove caching on GET request for PDF file and pdftxt which fixes loading wrong PDF files

**How to test manually**
* open a PDF file
* restart INCEpTION
* open another PDF file

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
I tried it in Safari, but didn't seem to work for me.

**Comment by wpmp** [comment]
@reckart well, that's unfortunate.
I could maybe add a random query parameter to the GET request, like the current time.
That should work, what do you think?

**Comment by reckart** [comment]
Adding a random query parameter should work.

**Comment by wpmp** [comment]
@reckart I changed it, hope it also works for safari now

**Pull request merged**
