### PR TITLE
#122 - kb relevant FeatureEditor refactor

### PR DESCRIPTION
**Pull request by MdeBoer95**
- move functions for retrieving instances and concepts to the knowledgebase service/ concept linking service

### CODE REVIEW

**Comment by naveen2507** [comment]
@MdeBoer95 I don't think we need some parts of `QueryUtil.java` anymore. Can you please remove the code which isn't in use anymore.

**Comment by MdeBoer95** [comment]
@naveen2507 All functions of ``QueryUtil.java`` are used in the ``ConceptLinkingService.java`` in some way.

**Comment by naveen2507** [comment]
@reckart this PR is ready for merge. Should we merge it or you want to wait for  #602?

**Comment by reckart** [comment]
I guess we should merge it so it doesn't become larger yet.

**Comment by naveen2507** [comment]
@reckart you can review this and then we can merge this.

**Pull request merged**
