### PR TITLE
#1708 - Disable YAGO

### PR DESCRIPTION
**Pull request by jcklie**
**What's in the PR**
- Add option to disable KB profiles
- Disable YAGO

**How to test manually**
* Try to find YAGO4 entry in remote KB creation dialog

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
Maybe add a comment in the JSON file why it is disabled?

**Comment by jcklie** [comment]
In the YAML?

**Comment by reckart** [comment]
Eh, yes - in the in YAML ;)

**Comment by reckart** [comment]
@jcklie looks like the PR was created on the wrong branch?

**Comment by jcklie** [comment]
It looks like it.

**Pull request closed without merging**
