### PR TITLE
#1732 - Upgrade dependencies (0.17.0)

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Spring Boot 2.2.6 -> 2.3.0
- Spring Security 5.2.3 -> 5.3.3

**How to test manually**
* No specific test procedure

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
What fails? Jenkins says it's ok?

**Comment by jcklie** [comment]
License Compliance — 2 issues found

**Comment by reckart** [comment]
That's only Fossa being paranoid. I just resolved that by telling Fossa to ignore the mysql driver.

**Comment by reckart** [comment]
... which I have to do every once in a while it appears ...

**Pull request merged**
