### PR TITLE
#1597 - Several format examples cannot be used copy-paste

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Disable auto-conversion of tabs to spaces

**How to test manually**
* Copy VRT example to a file and then try importing it

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
How did you build? On the command line or in Eclipse?

**Comment by UWinch** [comment]
I build on the console. I'm not sure what the problem might be, could you have a look at it again?

**Comment by reckart** [comment]
Ok, I found the problem. The `GenerateDocumentation` code tried to configure the `coderay` source-highlighter, but it actually didn't because it tried to do it as an attribute instead of an option. And therefore `tabsize` worked there because coderay wasn't turned on.

In the maven build, coderay was turned on and it does not seem to support `tabsize` meaning that the tabs were expanded.

I now removed coderay everywhere.

Mind that most format samples are sources from WebAnno, so we'll only get them once we upgrade to a WebAnno version which has them (i.e. > 4.0.0-beta-9). One which *is* now copyable is the "VRT" example which is sourced from INCEpTION.

**Comment by reckart** [comment]
Any objections against merging this one?

**Pull request merged**
