### PR TITLE
#719 - Active learning sidebar triggers concurrent access error

### PR DESCRIPTION
**Pull request by reckart**
- Update the access timestamp in the annotator state when saving the CAS to avoid concurrent access warning

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by Rentier** [comment]
This PR has the same problem with failing tests as #303

**Comment by reckart** [comment]
@Rentier build looks good now. Good for approval as well?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
