### PR TITLE
#1226 - Clean up PDFAnno code

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
- remove change comments

**How to test manually**
* Start INCEpTION
* Play around with PDF editor

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
@wpmp is it still WIP?

**Comment by wpmp** [comment]
@reckart yes, there are still a few minor things I want to look at

**Comment by reckart** [comment]
@wpmp could you please add a checklist to the initial description indicating what still remains to be done?

**Comment by wpmp** [comment]
@reckart I wanted to check the open TODOs in the code from paperai, however this is probably something for another PR some other day.
I just made the last change I had in mind.

If you want to review feel free to do so.
But please keep in mind that I currently don't have the time to test this last change however it shouldn't break anything as I only removed two query params that are never used. :)
Otherwise I could double check tonight if you don't want to review yet.

**Comment by reckart** [comment]
@wpmp there is no urgent need to merge it if you still can check things :) Better check for anything you may still have doubts on.

**Comment by reckart** [comment]
@wpmp let me know when you had time to test it

**Comment by wpmp** [comment]
@reckart seems to work, you can review

**Comment by wpmp** [comment]
Jenkins, can you test this please?

**Comment by wpmp** [comment]
Yes, that's true.
When I removed it I thought it wouldn't be used anyway as we build in another directory, however I forget that it is copied over beforehand.
Should I make a new commit adding it again or something else?

**Comment by reckart** [comment]
I guess since you changed the dependencies, it needs to be regenerated, right? So regenerate it and then add it to the PR?

**Comment by wpmp** [comment]
Done :)

**Pull request merged**
