### PR TITLE
#690 - Full text search against Virtuoso KBs not working if there are spaces

### PR DESCRIPTION
**Pull request by reckart**
- Quote the query in single quotes as Virtuoso requires it
- If possible, add an asterisk to the last word for a prefix query (same as we do for Lucene)

### CODE REVIEW

**Comment by reckart** [comment]
@naveen2507 @MdeBoer95 Do you have time to check/approve it?

**Comment by reckart** [comment]
I'd like to merge this for inclusion in the 0.6.3 release. It would be great if somebody could have a look / test / and approve (or not).

**Comment by reckart** [comment]
Are you testing against the UKP Virtuoso?

**Comment by naveen2507** [comment]
yeah .

image

**Comment by reckart** [comment]
@naveen2507 the FT mode is set to Lucene in your configuration - that will not work for Virtuoso. You need to change to "bif:contains".

**Comment by naveen2507** [comment]
oh yeah ..Sorry works now.

**Pull request merged**
