### PR TITLE
#880 - Selection of relations in PDF editor

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
* support for selecting relation annotations in PDF editor
* fixes tests for relation selection
* adding a missing extension marker in PDFAnno source

**How to test manually**
1. open a PDF file in PDF editor
2. create two spans
3. create a relation between those spans by drag and drop
4. select this relation

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by wpmp** [comment]
This PR is based on #930

**Comment by wpmp** [comment]
@reckart is it OK to have a PR like this?
The branch for this PR is based on the branch for issue #839 (PR is #930 )
Or should I close it and open another one once #930 is merged?

**Comment by reckart** [comment]
No, it's fine like this.

**Comment by reckart** [comment]
@wpmp could you please have a look at the conflict?

**Comment by wpmp** [comment]
Not sure why this was shown as a conflict, didn't get one when I merged on my device..

**Comment by wpmp** [comment]
@reckart shouldn't the tests work now with 6400113 ?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
