### PR TITLE
#947 - Removing recommendations in PDF editor

### PR DESCRIPTION
**Pull request by wpmp**
**What's in the PR**
* support for removing recommendations by double clicking span annotation knob

**How to test manually**
1. add a recommender
2. open a PDF document in PDF editor
3. double click the annotation knob of a recommendation

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by wpmp** [comment]
This PR is based on #951

**Comment by reckart** [comment]
@wpmp is this really WIP or is it already good to review?

**Comment by wpmp** [comment]
@reckart it is ready for review, just kept WIP because of the merging and branches stuff

**Comment by wpmp** [comment]
@reckart so, recommendations have its own color, right?
If that's true I could identify them in PDFAnno by its color.
Maybe I could change PDFAnno to render the dot to be of a different color, so all "normal" annotations would be blue and the recommendations would be like grey or so.
What do you think?

**Comment by reckart** [comment]
Yes, they have a different color - but that is not the point.

Let's say you have two suggestions for a given span, e.g. it could be a "LOC" or a "PER" - so there will be two blue dots. I cannot tell which one I'm accepting/rejecting before actually doing it.

**Comment by wpmp** [comment]
Ok, now I understand.
I guess I get the type of a suggestion by its layer?

**Comment by reckart** [comment]
See `de.tudarmstadt.ukp.clarin.webanno.api.annotation.util.TypeUtil.getUiLabelText(TypeAdapter, Map<String, String>)` and its usages.

**Comment by wpmp** [comment]
I created an issue #981

**Pull request merged**
