### PR TITLE
#946 - PubAnnotation connector for external search

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Clean up external search API in general
- Fixed external search service and UI such that it does actually support multiple repositories and providers
- Added PubAnnotation provider
- Added preliminary basic unit tests for ElasticSearch provider and PubAnnotation provider
- More compact display of the external search sidebar
- Use document ID instead of document title to import and to access imported documents
- Better UI feedback on successes and errors
- Retain section information when importing documents from PubAnnotation

**How to test manually**
* Create a document repository of type "PubAnnotation"
* Go to external search page and try a query
* Try viewing a document (click on title)
* Try importing a document
* Try same things via external search sidebar on annotation page

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
@rgabbard I have made some changes to the external search API as part of this PR - it would be great if you could have a look and see if it breaks anything for you... we're still struggling here getting our own ElasticSearch with Gigaword set up because we have the wrong gigaword version.

**Comment by reckart** [comment]
I'm planning to allow `ExternalSearchHighlight`s without offset information on account of not always having access to the document text to actually calculate them.

See: https://github.com/inception-project/inception/pull/846/files#r260029581

**Comment by reckart** [comment]
> One sidenote: When searching for a term like "organism", terms like "organo", "organic" or "organized" are highlighted in the results as well. Is this intended?

I don't know :) I have observed the same thing with a different search term and commented upstream:

https://github.com/pubannotation/pubannotation/issues/5#issuecomment-467192043

**Comment by reckart** [comment]
@rgabbard I think it might be a good idea if you actually try this branch out to see e.g. if documents you have previously imported still show up as imported on the search page/search sidebar.

**Comment by rgabbard** [comment]
@shinyichen , please check this out as requested by @reckart above

**Comment by shinyichen** [comment]
@reckart I am getting this error 
`com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "randomOrder" (class de.tudarmstadt.ukp.inception.externalsearch.elastic.traits.ElasticSearchProviderTraits), not marked as ignorable`
How can I mark `randomOrder` property as ignorable, just to be able to test this branch?

**Comment by jcklie** [comment]
@shinyichen You can add `@JsonIgnoreProperties(ignoreUnknown = true)` to `ElasticSearchProviderTraits`

**Comment by shinyichen** [comment]
Thank you @jcklie 
I have confirmed that previous imported documents show up as imported (external search and external search sidebar) on this branch.

**Pull request merged**
