### PR TITLE
Feature/174 comprehensive deletion for kb entities

### PR DESCRIPTION
**Pull request by MdeBoer95**

### CODE REVIEW

**Comment by naveen2507** [comment]
@MdeBoer95 Deleting an instance which has been annotated gives:

Are you sure you want to delete "Wine"?
Error: null

Here is the stack trace:
```
java.lang.UnsupportedOperationException: null
	at de.tudarmstadt.ukp.inception.kb.reification.WikiDataReification.delete(WikiDataReification.java:310) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.kb.reification.WikiDataReification.deleteInstance(WikiDataReification.java:292) ~[classes/:?]
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.deleteInstance(KnowledgeBaseServiceImpl.java:523) ~[classes/:?]

```

**Comment by MdeBoer95** [comment]
The Exception is thrown because the delete-method for WikiDataReification has not been implemented yet. What we said in the last meeting with @reckart was, that someone else is going to do that.

**Comment by MdeBoer95** [comment]
> Can we give a better error method here, maybe with a popup.

Not sure what exactly you mean. Is there no error message displayed in the feedback panel?

**Comment by naveen2507** [comment]
image


Here is the screenshot. 
On Confirm click, it doesn't do anything for me.

**Comment by MdeBoer95** [comment]
Does this KB have WikiDataReification?
I think this won't happen anymore once the corresponding delete method has been implemented.

**Comment by naveen2507** [comment]
WikiDataReification issue will have to be checked once the corresponding delete method has been implemented. @MdeBoer95 can u raise the issue for this?

**Comment by naveen2507** [comment]
Dependence on #140 . @MdeBoer95 is working with @matchlesswei on this.

**Comment by MdeBoer95** [comment]
I would suggest to finish it (including the delete method in WikiDataReification) on this branch and then merge it. As issue #174 is scheduled for 0.5, I was planning to do this next month and prioritise other issues for now.

**Comment by naveen2507** [comment]
@MdeBoer95 did you get time to look into this issue with @matchlesswei ?

**Pull request merged**
