### PR TITLE
Updated explanation why/how to create a relation layer

### PR DESCRIPTION
**Pull request by jfiala**
**What's in the PR**
Update documentation on how to use relations/create a relation layer.

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by jfiala** [comment]
looks great :).
Maybe a screenshot of the layer screen would be helpful as well?

**Comment by reckart** [comment]
The part of the documentation we are modifying here belongs to the annotation page - more detailed information about how to configure a layer should rather be in the documentation for the project settings layers panel.

**Comment by jfiala** [comment]
OK fine, I think the updated version looks great, can be merged :).

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
