### PR TITLE
Upgrade to Matomo Java Tracker 3.2.0

### PR DESCRIPTION
**Pull request by dheid**
### Hey @reckart and team,

Just wanted to give your project a little boost with the latest and greatest from Matomo Java Tracker! 🚀

### Changes in a Nutshell:

- **Bug Fixes & Performance Boosts:** Say goodbye to some pesky bugs and enjoy a faster, smoother tracking experience.

- **Security Makeover:** We're getting the latest security swag to keep our project locked down.

- **Stay Cool with Compatibility:** Now we're best buddies with Matomo versions up to 5, so no more awkward compatibility issues.

- **Less Baggage:** Matomo Java Tracker 3.2.0 is lean and mean with fewer dependencies. Less stuff, more speed!

- **New Toys:** Check out the cool new dimension parameter for super-customizable tracking.

- **Java 11 Party:** We're upgrading to the latest Java 11 implementation. It's like giving our project a cool new set of wheels.

- **Smooth Moves:** If you're coming from version 2, no worries! There's a handy migration guide [here](https://github.com/matomo-org/matomo-java-tracker#migration-from-version-2-to-302) to make the switch painless.

### How to Test:

1. Update to Matomo Java Tracker version 3.2.0.
2. Make sure our project still builds like a champ.
3. Double-check that our Matomo tracking mojo is still on point.
4. Test out any new features and give that dimension parameter a spin.

### Where to Get Help:

- Dive into the [Javadoc](https://javadoc.io/doc/org.piwik.java.tracking/matomo-java-tracker-core/3.2.0/index.html) for the nitty-gritty details.
- Got issues or bright ideas? Hit up the [Matomo Java Tracker GitHub](https://github.com/matomo-org/matomo-java-tracker).

### Your Feedback Matters:

Give it a whirl and let us know how it goes! Your feedback is like gold to us. 🌟

Cheers,
Daniel

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Thanks for the update @dheid. Will look into it.

**Comment by dheid** [comment]
Thank you, @reckart! I did some cleanups to the code.

**Comment by reckart** [comment]
@dheid For curiosity - what is your motivation for submitting the PR?

**Comment by reckart** [comment]
It may take a moment for me to look into this because it turns out that I first need to do some maintenance on our Matomo instance first... 😮‍💨

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@dheid Do I understand it correctly that the 3.2.0 client library is no longer compatible with Matomo 3?

**Comment by dheid** [comment]
@reckart The tracking API for Matomo version 3 (https://github.com/matomo-org/developer-documentation/blob/live/docs/3.x/tracking-api.md) does not differ much from the latest version. I think it's compatible, but I didn't test it as Matomo version 3 is no longer supported.

**Comment by reckart** [comment]
@dheid Why did you close it?

**Comment by reckart** [comment]
@dheid I closed it because I did not have time to upgrade the Matomo server at the time. Recently, I found the time to finally upgrade the server. Now I am also upgrading the library.

**Comment by reckart** [comment]
Superseded by https://github.com/inception-project/inception/pull/5496

**Comment by reckart** [comment]
@dheid You had asked for feedback. First thing I noticed is that the java11 flavor doesn't allow turning off SSL verification, so I had to switch to the java8 flavour. Still need to test that it still works. I didn't have time to look into replacing the custom variables with the modern approach.

**Comment by reckart** [comment]
@dheid Looks like I still get telemetry after the update 👍

**Comment by dheid** [comment]
Thanks for the feedback! I think it is preferable to not have dependencies, because it is always possible to add a certificate to the truststore and that's how custom certificates are usually used in the Java world in my experience. But it is a missing "feature" to disable SSL checks nevertheless. But it seems as insecure as using plain HTTP.

**Pull request closed without merging**
