### PR TITLE
#1243 - PF4J-based plugin system for INCEpTION

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Added three new modules: plugin-manager, plugin-api and plugin-parent
- Converted DL4J and Data Majority modules to plugins
- Hook plugin manager into web application

**How to test manually**
* Build the entire project
* Copy the files `inception-example-imls-data-majority-0.10.0-SNAPSHOT-plugin.jar` and `inception-imls-dl4j-0.10.0-SNAPSHOT-plugin.jar` from the `target` folders of their respective modules into `~/.inception/plugins` (replace `~/.inception` according to your usual local setup).
* Start the application and try using the Data Majority or DL4J recommenders

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by jcklie** [comment]
This looks very nice. One small thing: We use the datamajority thingy only as an example in the documentation, so you can use it also as an example on how to create plugins; you might also need to check whether the documentation of creating a recommender makes sense now that it is a plugin.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@jcklie ok, builds...

**Comment by reckart** [comment]
Eventually yes, but it would go into WebAnno I suppose.

**Pull request merged**
