### PR TITLE
#2612 - Add possibility to enforce singelton document level annotations

### PR DESCRIPTION
**Pull request by reckart**
**What's in the PR**
- Add option to mark a document metadata layer as a singleton
- Route DocumentOpenedEvents to the UI so the DocumentMetadataSidebar can react and initialize the singletons
- Put delete button direclty into the sidebar without wrapping it in a dropdown

**How to test manually**
* Mark a document metadata layer as singleton
* Open annotation page, open metadata sidebar, enter data, switch between documents

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by jcklie** [comment]
It works, the only issue I had was that I needed to open a document twice to create the singleton annotation. I think after the second open it was available in all documents thoug.

https://gyazo.com/5d87c97f4d54516db7800b0e4809379d

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by UWinch** [comment]
It is no longer possible for me to create other annotations (except the document metadata), the right sidebar is missing. This is also the case if no document metadata layer is configured.

**Comment by reckart** [comment]
The right sidebar should only be missing if there is no "regular" layer and only document-metadata layers. As long as any span/relation/chain layer exists, the right sidebar should be visible.

**Comment by reckart** [comment]
@UWinch the sidebar missing issue should be fixed now.

**Pull request merged**
