### PR TITLE
#136 - Allow concepts that are not explicitly class instances

### PR DESCRIPTION
**Pull request by reckart**
- Improve listing of root concepts (but also slower)
- List child concepts even if they do not have an explicit instance-of statement
- Allow reading a KBConcept even if it does not have an explicit instance-of statement

### CODE REVIEW

**Comment by naveen2507** [comment]
I think we can close this pull request.

**Comment by reckart** [comment]
@naveen2507 you mean close without merging?

**Comment by naveen2507** [comment]
@reckart yeah. Or, would be better if we can discuss about some issues on this. I have some doubts about the implementation for concept tree on the line of Protege. We can then decide about closing this pull request.

**Comment by reckart** [comment]
@naveen2507 well, we apparently have two PRs now for issue #136. Did you build your changes on mine or do your changes supersede mine?

**Comment by naveen2507** [comment]
@reckart I am closing this pull request.

**Comment by naveen2507** [comment]
Superseded by PR  #280

**Pull request closed without merging**
