### PR TITLE
Feature/296 move definition of knowledge base profiles into a file

### PR DESCRIPTION
**Pull request by MdeBoer95**

### CODE REVIEW

**Comment by MdeBoer95** [comment]
It works with this constructor.
https://github.com/inception-project/inception/blob/aec258d5192ad2a845423c278f0353134b852271/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseMapping.java#L35-L50

 So why not use it like that?

**Comment by Rentier** [comment]
You could also implement Jackson Serializer and Deserializer for this, it is not so difficult. E.g. http://www.baeldung.com/jackson-custom-serialization

**Comment by reckart** [comment]
I'm a bit worried if it is by design or accidental that the values are serialized correctly from IRI to string. But ok. In fact, we use this only for deserialization, not for serialization. So if we have a unit test for deserialization that works, let's leave it at the solution with the constructor that you propose. However, please also include a no-args constructor. Serializable classes should always have one.

**Comment by MdeBoer95** [comment]
The custom Serializer/Deserializer is nice but I think a it's a bit overkill for this. I will just implement a unit test for now.

**Comment by reckart** [comment]
@MdeBoer95 the build fails, but I assume the PR is still a work-in-progress, right? Could you please add the tag "WIP"?

**Comment by MdeBoer95** [comment]
It is basically done. I don't know why the tests fail, they are all successful on my local machine.

**Comment by reckart** [comment]
Why do `KnowledgeBaseProfile` and `KnowledgeBaseMapping` require a hashcode/equals implementation?

**Pull request merged**
