### PR TITLE
#3321 - Fix typos in code and documentation

### PR DESCRIPTION
**Pull request by stweil**
Most of them were found in documentation, comments and messages.
A few typos were in the names of local functions or variables.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

**Documentation**
* [x] PR updates documentation

### CODE REVIEW

**Comment by stweil** [comment]
Most modifications were created automatically by running `codespell -sw` and selecting the relevant ones.

**Review by reckart — APPROVED** [review]

**Comment by reckart** [comment]
Cool, thanks!

I did see a rename of a local variable - but I didn't notice any functions/methods being renamed.

**Comment by reckart** [comment]
Jenkins, can you test this pleaseß

**Comment by stweil** [comment]
> I did see a rename of a local variable - but I didn't notice any functions/methods being renamed.

Nor did I while reviewing my own commit again. I found variables `received` and `occurrences`. Should I update the commit message?

**Comment by stweil** [comment]
I also noticed at least one German typo `Possessivpronome`. Maybe you can simply fix that yourself. Or should I send a pull request for that as well?

**Comment by stweil** [comment]
@reckart, I started using inception today by installing it on one of our Debian servers and noticed that the admin guide is still based on Debian Stretch (= oldoldstable, unsupported). It needs updates for 25.0 to work with Debian stable or testing.

**Comment by reckart** [comment]
@stweil Contributions are always welcome! And update for the installation documentation to stable would surely be welcome. Unfortunately, I can't try the validator on our own servers because it seems to be lacking the necessary certificates in our certificate chain - so no idea what the issues that it reports to you would imply in terms of changes. I you already find issues on the login page, I wonder what could be found on the pages after a successful login...

If you open issues for the things you consider working on and refer to them in the style we usually do it in the commit messages, then I could use a history-maintaining "merge" operation when - otherwise, I'd have to use a squash to get the opportunity to rewrite the merge message.

**Comment by stweil** [comment]
> I can't try the validator on our own servers

Use your web browser to copy the HTML code of a web page and paste it into the validator (https://validator.w3.org/#validate_by_input). That will always work (see also issue #3326 where I used that for the project overview page).

**Pull request merged**
